
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-05-08T12:04:42+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "89c0a4fea802ac87dfa052c6385a3044fa412fdb",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
