
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "ecdae84aa3b8ee5408876b0b7d7eade3d127e177",
 "version": "0.15.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
