from ...tl.mtproto_request import MTProtoRequest


class InputReportReasonSpam(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    inputReportReasonSpam#58dbcab8  = ReportReason"""

    # Telegram's constructor ID (and unique identifier) for this class
    constructor_id = 0x58dbcab8

    def __init__(self):
        super().__init__()

    def on_send(self, writer):
        writer.write_int(InputReportReasonSpam.constructor_id, signed=False)

    @staticmethod
    def empty():
        """Returns an "empty" instance (all attributes are None)"""
        return InputReportReasonSpam()

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'inputReportReasonSpam#58dbcab8  = ReportReason'

    def __str__(self):
        return '(inputReportReasonSpam (ID: 0x58dbcab8) = ())'.format()
