# coding: utf-8

"""
    DDOTS RESTful API Server

    ## Explore the demo server  I suggest you start with signing up a new user. To do so, use `POST /users/` endpoint with `recaptcha_key=\"secret_key\"`.  You will need to know the API Client ID to authenticate, so here it is: `documentation`. Sometimes (e.g. for token refreshing) you might need API Client Secret: `KQ()SWK)SQK)QWSKQW(SKQ)S(QWSQW(SJ*HQ&HQW*SQ*^SSQWSGQSG`.  There are also two built-in users: * `root` (administrator with all permissions) with password `q` * `user` (regular user) with password `w` 

    OpenAPI spec version: 0.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import ddots_client
from ddots_client.rest import ApiException
from ddots_client.apis.auth_api import AuthApi


class TestAuthApi(unittest.TestCase):
    """ AuthApi unit test stubs """

    def setUp(self):
        self.api = ddots_client.apis.auth_api.AuthApi()

    def tearDown(self):
        pass

    def test_create_oauth_client(self):
        """
        Test case for create_oauth_client

        Create a new OAuth2 Client
        """
        pass

    def test_get_o_auth2_clients(self):
        """
        Test case for get_o_auth2_clients

        List of OAuth2 Clients
        """
        pass

    def test_options_o_auth2_clients(self):
        """
        Test case for options_o_auth2_clients

        Check which methods are allowed
        """
        pass


if __name__ == '__main__':
    unittest.main()
