
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-05-06T16:53:44-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "a82aeab4ccdd5c466464fe27d5ec850dc8f7beeb",
 "version": "0.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
