
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-05-08T14:48:47+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "a8f7c0cc4edcdd6634ea9695cd1755ccdf2481ac",
 "version": "0.6.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
