# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rst/kinematics/JointPositionState.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import rst.kinematics.JointState_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rst/kinematics/JointPositionState.proto',
  package='rst.kinematics',
  serialized_pb='\n\'rst/kinematics/JointPositionState.proto\x12\x0erst.kinematics\x1a\x1frst/kinematics/JointState.proto\"@\n\x12JointPositionState\x12*\n\x06joints\x18\x01 \x03(\x0b\x32\x1a.rst.kinematics.JointStateB\x18\x42\x16JointPositionStateType')




_JOINTPOSITIONSTATE = _descriptor.Descriptor(
  name='JointPositionState',
  full_name='rst.kinematics.JointPositionState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='joints', full_name='rst.kinematics.JointPositionState.joints', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=92,
  serialized_end=156,
)

_JOINTPOSITIONSTATE.fields_by_name['joints'].message_type = rst.kinematics.JointState_pb2._JOINTSTATE
DESCRIPTOR.message_types_by_name['JointPositionState'] = _JOINTPOSITIONSTATE

class JointPositionState(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _JOINTPOSITIONSTATE

  # @@protoc_insertion_point(class_scope:rst.kinematics.JointPositionState)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'B\026JointPositionStateType')
# @@protoc_insertion_point(module_scope)
