
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "c431167af4bb4415787c7b6193838cfb85f2a2d2",
 "version": "0.1.1.post9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
