# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rst/robot/PickAndPlaceActionCollection.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import rst.robot.PickAndPlaceAction_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rst/robot/PickAndPlaceActionCollection.proto',
  package='rst.robot',
  serialized_pb='\n,rst/robot/PickAndPlaceActionCollection.proto\x12\trst.robot\x1a\"rst/robot/PickAndPlaceAction.proto\"N\n\x1cPickAndPlaceActionCollection\x12.\n\x07\x65lement\x18\x01 \x03(\x0b\x32\x1d.rst.robot.PickAndPlaceActionB\"B PickAndPlaceActionCollectionType')




_PICKANDPLACEACTIONCOLLECTION = _descriptor.Descriptor(
  name='PickAndPlaceActionCollection',
  full_name='rst.robot.PickAndPlaceActionCollection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='element', full_name='rst.robot.PickAndPlaceActionCollection.element', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=95,
  serialized_end=173,
)

_PICKANDPLACEACTIONCOLLECTION.fields_by_name['element'].message_type = rst.robot.PickAndPlaceAction_pb2._PICKANDPLACEACTION
DESCRIPTOR.message_types_by_name['PickAndPlaceActionCollection'] = _PICKANDPLACEACTIONCOLLECTION

class PickAndPlaceActionCollection(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PICKANDPLACEACTIONCOLLECTION

  # @@protoc_insertion_point(class_scope:rst.robot.PickAndPlaceActionCollection)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'B PickAndPlaceActionCollectionType')
# @@protoc_insertion_point(module_scope)
