# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rst/monitoring/ProcessCuesCollection.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import rst.monitoring.ProcessCues_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rst/monitoring/ProcessCuesCollection.proto',
  package='rst.monitoring',
  serialized_pb='\n*rst/monitoring/ProcessCuesCollection.proto\x12\x0erst.monitoring\x1a rst/monitoring/ProcessCues.proto\"E\n\x15ProcessCuesCollection\x12,\n\x07\x65lement\x18\x01 \x03(\x0b\x32\x1b.rst.monitoring.ProcessCuesB\x1b\x42\x19ProcessCuesCollectionType')




_PROCESSCUESCOLLECTION = _descriptor.Descriptor(
  name='ProcessCuesCollection',
  full_name='rst.monitoring.ProcessCuesCollection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='element', full_name='rst.monitoring.ProcessCuesCollection.element', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=96,
  serialized_end=165,
)

_PROCESSCUESCOLLECTION.fields_by_name['element'].message_type = rst.monitoring.ProcessCues_pb2._PROCESSCUES
DESCRIPTOR.message_types_by_name['ProcessCuesCollection'] = _PROCESSCUESCOLLECTION

class ProcessCuesCollection(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PROCESSCUESCOLLECTION

  # @@protoc_insertion_point(class_scope:rst.monitoring.ProcessCuesCollection)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'B\031ProcessCuesCollectionType')
# @@protoc_insertion_point(module_scope)
