from ...tl.mtproto_request import MTProtoRequest


class InputMediaEmpty(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    inputMediaEmpty#9664f57f  = InputMedia"""

    # Telegram's constructor ID (and unique identifier) for this class
    constructor_id = 0x9664f57f

    def __init__(self):
        super().__init__()

    def on_send(self, writer):
        writer.write_int(InputMediaEmpty.constructor_id, signed=False)

    @staticmethod
    def empty():
        """Returns an "empty" instance (all attributes are None)"""
        return InputMediaEmpty()

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'inputMediaEmpty#9664f57f  = InputMedia'

    def __str__(self):
        return '(inputMediaEmpty (ID: 0x9664f57f) = ())'.format()
