from ...tl.mtproto_request import MTProtoRequest


class SendMessageGamePlayAction(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    sendMessageGamePlayAction#dd6a8f48  = SendMessageAction"""

    # Telegram's constructor ID (and unique identifier) for this class
    constructor_id = 0xdd6a8f48

    def __init__(self):
        super().__init__()

    def on_send(self, writer):
        writer.write_int(SendMessageGamePlayAction.constructor_id, signed=False)

    @staticmethod
    def empty():
        """Returns an "empty" instance (all attributes are None)"""
        return SendMessageGamePlayAction()

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'sendMessageGamePlayAction#dd6a8f48  = SendMessageAction'

    def __str__(self):
        return '(sendMessageGamePlayAction (ID: 0xdd6a8f48) = ())'.format()
