# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyHealth',
            fields=[
                ('uid', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('state', jsonfield.fields.JSONField(blank=True, default={}, null=True)),
                ('severity', jsonfield.fields.JSONField(blank=True, default={}, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeartHealthTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(db_index=True)),
                ('time', models.DateTimeField()),
                ('heartrate', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SleepHealthTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(db_index=True)),
                ('time', models.DateTimeField()),
                ('hours', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
