# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rst/timing/Frequency.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rst/timing/Frequency.proto',
  package='rst.timing',
  serialized_pb='\n\x1arst/timing/Frequency.proto\x12\nrst.timing\"\x17\n\tFrequency\x12\n\n\x02hz\x18\x01 \x02(\x01\x42\x0f\x42\rFrequencyType')




_FREQUENCY = _descriptor.Descriptor(
  name='Frequency',
  full_name='rst.timing.Frequency',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hz', full_name='rst.timing.Frequency.hz', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=42,
  serialized_end=65,
)

DESCRIPTOR.message_types_by_name['Frequency'] = _FREQUENCY

class Frequency(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FREQUENCY

  # @@protoc_insertion_point(class_scope:rst.timing.Frequency)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'B\rFrequencyType')
# @@protoc_insertion_point(module_scope)
