# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rst/timing/IntervalCollection.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import rst.timing.Interval_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rst/timing/IntervalCollection.proto',
  package='rst.timing',
  serialized_pb='\n#rst/timing/IntervalCollection.proto\x12\nrst.timing\x1a\x19rst/timing/Interval.proto\";\n\x12IntervalCollection\x12%\n\x07\x65lement\x18\x01 \x03(\x0b\x32\x14.rst.timing.IntervalB\x18\x42\x16IntervalCollectionType')




_INTERVALCOLLECTION = _descriptor.Descriptor(
  name='IntervalCollection',
  full_name='rst.timing.IntervalCollection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='element', full_name='rst.timing.IntervalCollection.element', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=78,
  serialized_end=137,
)

_INTERVALCOLLECTION.fields_by_name['element'].message_type = rst.timing.Interval_pb2._INTERVAL
DESCRIPTOR.message_types_by_name['IntervalCollection'] = _INTERVALCOLLECTION

class IntervalCollection(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INTERVALCOLLECTION

  # @@protoc_insertion_point(class_scope:rst.timing.IntervalCollection)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'B\026IntervalCollectionType')
# @@protoc_insertion_point(module_scope)
