
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-06-01T08:26:24-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "5b2772e62335f6a1a117374d4b50779dded7bcd3",
 "version": "0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
