def chicken():
  print("      ,~.")
  print("   ,-'__ `-,")
  print("  {,-'  `. }              ,')")
  print(",( a )   `-.__         ,',')~,")
  print("<=.) (         `-.__,==' ' ' '}")
  print("  (   )                      /)")
  print("   `-'\   ,                    )")
  print("       |  \        `~.        /")
  print("      \   `._        \      /")
  print("        \     `._____,'    ,'")
  print("         `-.             ,'")
  print("            `-._     _,-'")
  print("                77jj'")
  print("               //_||")
  print("            __//--'/` ")
  print("          ,--'/`  '")
  
