
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-05-22T16:07:04-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "cc64cd5b38f9de0cc318776e2625c43c2c8b8ade",
 "version": "0.1.0b3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
