
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "928f081b8bf435e657a4707fd6ec94f23135eebd",
 "version": "0.9.6post1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
