BBBB BBBBBB BBBB BBBBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
  XXXX XXX XXXXX X XXXX XXXX XXXXXX XXXX XXXXX XX XXX XXXXX XXX XXXXX XXXX XXXXXXX XXXX XXXX XXXXXXX XXXXX XXXX XXX
  XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
  XXXXX XXXXXXXXXXXXX XXXXXXXXXXX

  XXXXXXXBBBBB BBBBB gettext(u'Service form') BBBBBBBBXXXXXXXX
  BBBBB BBB
    BBBBBBBB BBB
      XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    BBBBBBBBBBB
  BBBBBBBB
XXXXXXX

XXXXXX

XXXX XXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXX
      BBBBB BBBBBB
      BBBBBBBB
      XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        BBBBB BBBBBBBBBBBBBBBBB
        XXXXXXXXXXXXXXXXX
        BBBBBBBB
      XXXXX
      BBBBB BBBBBBBB
        BB BBBBBBBB
          XXX XXXXXXXXXXXXXXXXX
            BBB BBBBBBB BB BBBBBBBB
              XXXXBB BBBBBBBBBBBB XXXXXXXXXXXX XXXXXXXBBBBBXXXXXXX
            BBBBBB
          XXXXX
        BBBBB
      BBBBBBBB
      BBBBB BBBBBBB
        XXX XXX XXXX
      BBBBBBBB
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXX XXXX XXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
XXXX XXXXXX XX XXX XXX XX XXX XXXXXXXX XX XXX XXXXX XXXX XXXXXX XXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXXX
  XXXXXXXXXXXX X
    BBBBB BBBBBBBBBB
    BBBBBBBB
  XXX
XXXXXXXXX
XXXXXXX
XXXXXXX