BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBB BBBBBBB
  BBBB BBBB
  XXXXXXXXX
  XXX
    FFFFFFFFFFFF
  XXXX
  

  BBB BBBBBBBBB BB BBBBBBBBBBBBBB
    
    XXXX XXXXX
    BB BBBBBBBBBBBBBBBBBBBBB
      XXX
        FFFFFFFFFFFF
      XXXX
    BBBBB
    BBB BBBBBBBBB BB BBBBBBBBBBBBBBBBBBB
      
      XXXX XXXXX
      BB BBBBBBBBBBBBBBBBBBBBB
        XXX
          FFFFFFFFFFFF
        XXXX
      BBBBB
      
      XXXX
        BBB BBBBBBBB BB BBBBBBBBBBBBBBBBBBB
          XXX XXXXXXXXX   BB BBBBBBBBBBBBBBBBBBBB XXBBBBBXXXXX

          BB BBBBBBBBBBBBBBBBBBBB
            XXX XXXXXXXXX
              BBB BBBBBB BB BBBBBBBBBBBBBBBBBB
                XXXXBB BBBBBBBBBBBBBBBBBB XXBBBBBXXXXX
              BBBBBB
            XXXXX
          BBBBB
        BBBBBB
      XXXXX
    BBBBBB
  BBBBBB

BBBBBBBB
