# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rst/scene/SceneObjectQuery.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rst/scene/SceneObjectQuery.proto',
  package='rst.scene',
  serialized_pb='\n rst/scene/SceneObjectQuery.proto\x12\trst.scene\"D\n\x10SceneObjectQuery\x12\x17\n\x0bname_filter\x18\x01 \x01(\t:\x02.*\x12\x17\n\x0bkind_filter\x18\x02 \x01(\t:\x02.*B\x16\x42\x14SceneObjectQueryType')




_SCENEOBJECTQUERY = _descriptor.Descriptor(
  name='SceneObjectQuery',
  full_name='rst.scene.SceneObjectQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name_filter', full_name='rst.scene.SceneObjectQuery.name_filter', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode(".*", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kind_filter', full_name='rst.scene.SceneObjectQuery.kind_filter', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode(".*", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=47,
  serialized_end=115,
)

DESCRIPTOR.message_types_by_name['SceneObjectQuery'] = _SCENEOBJECTQUERY

class SceneObjectQuery(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SCENEOBJECTQUERY

  # @@protoc_insertion_point(class_scope:rst.scene.SceneObjectQuery)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'B\024SceneObjectQueryType')
# @@protoc_insertion_point(module_scope)
