from ...tl.mtproto_request import MTProtoRequest


class ContactLinkHasPhone(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    contactLinkHasPhone#268f3f59  = ContactLink"""

    # Telegram's constructor ID (and unique identifier) for this class
    constructor_id = 0x268f3f59

    def __init__(self):
        super().__init__()

    def on_send(self, writer):
        writer.write_int(ContactLinkHasPhone.constructor_id, signed=False)

    @staticmethod
    def empty():
        """Returns an "empty" instance (all attributes are None)"""
        return ContactLinkHasPhone()

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'contactLinkHasPhone#268f3f59  = ContactLink'

    def __str__(self):
        return '(contactLinkHasPhone (ID: 0x268f3f59) = ())'.format()
