# coding=utf-8

import utils
import parseJATS as parser

def main():
    titles = []
    titles.append('Adaptive Evolution')
    titles.append('Adaptive evolution')
    titles.append('Aging')
    titles.append('Amyloid-beta peptides')
    titles.append('Angiogenesis')
    titles.append('Animal Models Of Disease')
    titles.append('Animal-microbe Interactions')
    titles.append('Antibacterial Response')
    titles.append('Antibiotics')
    titles.append('Antibody engineering')
    titles.append('Antimicrobial Resistance')
    titles.append('Antimicrobials')
    titles.append('Apoptosis')
    titles.append('Ascorbate Biosynthesis')
    titles.append('Associative Memory')
    titles.append('Autism Spectrum Disorders')
    titles.append('Autoimmune disorders')
    titles.append('Autoimmunity')
    titles.append('Autophagy')
    titles.append('Axon Growth')
    titles.append('B-cell Lymphoma')
    titles.append('Bacteria')
    titles.append('Bacterial Proliferation')
    titles.append('Biochemistry')
    titles.append('Bioinformatics')
    titles.append('Biosensors')
    titles.append('Birdsong')
    titles.append('Book Review')
    titles.append('Breast cancer')
    titles.append('Breathing')
    titles.append('Cancer')
    titles.append('Cancer Prevention')
    titles.append('Cancer metabolism')
    titles.append('Carcinogenesis')
    titles.append('Cardiac development')
    titles.append('Careers')
    titles.append('Cell Biology')
    titles.append('Cell Division')
    titles.append('Cell Fate Choice')
    titles.append('Cell cycle')
    titles.append('Cell division')
    titles.append('Cell proliferation')
    titles.append('Cellular Signalling')
    titles.append('Cerebellar Malformation')
    titles.append('Checkpoint Proteins')
    titles.append('Chemical Biology')
    titles.append('Chemical Informatics')
    titles.append('Chemotaxis')
    titles.append('Chromatin')
    titles.append('Chromatin mapping')
    titles.append('Chromosome Segregation')
    titles.append('Chromosomes')
    titles.append('Circadian Rhythms')
    titles.append('Co-evolution')
    titles.append('Cognition')
    titles.append('Collective Behaviour')
    titles.append('Communication')
    titles.append('Comparative Genomics')
    titles.append('Computational Biology')
    titles.append('Connectomics')
    titles.append('Convergent Evolution')
    titles.append('Craniosynostosis')
    titles.append('Crops and Climate Change')
    titles.append('Cryo-EM')
    titles.append('Cutting Edge')
    titles.append('Cutting edge')
    titles.append('Cystic Kidney Disease')
    titles.append('Cytoskeleton')
    titles.append('DNA Damage')
    titles.append('DNA Helicases')
    titles.append('DNA Methylation')
    titles.append('DNA Repair')
    titles.append('DNA repair')
    titles.append('DNA replication')
    titles.append('Decision making')
    titles.append('Development')
    titles.append('Developmental Neurobiology')
    titles.append('Developmental neuroscience')
    titles.append('Diabetes')
    titles.append('Dopamine System')
    titles.append('Echolocation')
    titles.append('Electron Microscopy')
    titles.append('Emerging Technology')
    titles.append('Endocytosis')
    titles.append('Endoplasmic reticulum')
    titles.append('Epidemiology')
    titles.append('Epigenetic Markers')
    titles.append('Epigenetics')
    titles.append('Evolution')
    titles.append('Evolutionary Developmental Biology')
    titles.append('Evolutionary Morphology')
    titles.append('Evolutionary biology')
    titles.append('Experimental Evolution')
    titles.append('Extinction Risk')
    titles.append('Face Recognition')
    titles.append('Flagellar Beating')
    titles.append('Flagellar Growth')
    titles.append('Focal adhesions')
    titles.append('Foot and Mouth Disease')
    titles.append('Functional MRI')
    titles.append('Gene Expression')
    titles.append('Gene Regulation')
    titles.append('Gene Therapy')
    titles.append('Gene expression')
    titles.append('Genetic Diseases')
    titles.append('Genetic rearrangement')
    titles.append('Genetic screen')
    titles.append('Genetic screening')
    titles.append('Genetics')
    titles.append('Genome Engineering')
    titles.append('Genomics')
    titles.append('Germ granules')
    titles.append('HIV')
    titles.append('HIV Cure Research')
    titles.append('Haematopoietic Stem Cells')
    titles.append('Hearing')
    titles.append('Heat shock response')
    titles.append('Hematopoiesis')
    titles.append('Hematopoietic Stem Cells')
    titles.append('Holoenzymes')
    titles.append('Horizontal Gene Transfer')
    titles.append('Host-microbe Interactions')
    titles.append('Host-pathogen Interactions')
    titles.append('Host-virus interactions')
    titles.append('Human Evolution')
    titles.append('Human Genetics')
    titles.append('Hypoxia')
    titles.append('Imaging')
    titles.append('Immune Response')
    titles.append('Immunometabolism')
    titles.append('Infectious Disease')
    titles.append('Infectious Diseases')
    titles.append('Innate like lymphocytes')
    titles.append('Interspecies Signalling')
    titles.append('Intracellular bacteria')
    titles.append('Ion Channels')
    titles.append('Ion channels')
    titles.append('Language')
    titles.append('Learning')
    titles.append('Learning and Memory')
    titles.append('Live-cell Imaging')
    titles.append('Living Science')
    titles.append('Living science')
    titles.append('Long distance transport')
    titles.append('Longevity')
    titles.append('Lung Disease')
    titles.append('Lysine Deactylases')
    titles.append('Magnetogenetics')
    titles.append('Magnetosensation')
    titles.append('Malaria')
    titles.append('Male Mating Behaviour')
    titles.append('Mass Spawning')
    titles.append('Mass Spectrometry')
    titles.append('Mathematical Modeling')
    titles.append('Mathematical modeling')
    titles.append('Mating Behaviour')
    titles.append('Meiosis')
    titles.append('Meiotic Drivers')
    titles.append('Membrane Fusion')
    titles.append('Membrane Protein Topology')
    titles.append('Membrane Proteins')
    titles.append('Membrane structures')
    titles.append('Memory')
    titles.append('Metabolism')
    titles.append('Metagenomics')
    titles.append('Metal Biology')
    titles.append('Metal Transport')
    titles.append('Microbial Ecology')
    titles.append('Microbial Evolution')
    titles.append('Microbiome')
    titles.append('Microbiota')
    titles.append('Microscopy')
    titles.append('Microtubules')
    titles.append('Mitochondria')
    titles.append('Mitosis')
    titles.append('Molecular Motors')
    titles.append('Molecular communication')
    titles.append('Motion Perception')
    titles.append('Motor Proteins')
    titles.append('Motor circuits')
    titles.append('Motor control')
    titles.append('Motor networks')
    titles.append('Multicellularity')
    titles.append('Mutations')
    titles.append('Natural Products')
    titles.append('Neural Circuits')
    titles.append('Neural Connectivity')
    titles.append('Neural Processing')
    titles.append('Neural circuits')
    titles.append('Neural coding')
    titles.append('Neural wiring')
    titles.append('Neuroblasts')
    titles.append('Neurogenesis')
    titles.append('Neuroimaging')
    titles.append('Neuropathic Pain')
    titles.append('Neuropharmacology')
    titles.append('Neurophysiology')
    titles.append('Neuropsychiatric Disorders')
    titles.append('Neuroscience')
    titles.append('Nitrogen Fixation')
    titles.append('Obesity')
    titles.append('Olfaction')
    titles.append('Oncogenesis')
    titles.append('Ophthalmology')
    titles.append('Organ Plasticity')
    titles.append('Organ Size')
    titles.append('Organoids')
    titles.append('Orofacial Coordination')
    titles.append('Palaeobiology')
    titles.append('Paleontology')
    titles.append('Paleoproteomics')
    titles.append('Pancreatic Cancer')
    titles.append('Parasites')
    titles.append('Parasitism')
    titles.append('Paternal effects')
    titles.append('Peer Review')
    titles.append('Perception')
    titles.append('Phage Predation')
    titles.append('Pheromones')
    titles.append('Photosynthesis')
    titles.append('Phototaxis')
    titles.append('Phylogenomics')
    titles.append('Phylogeny')
    titles.append('Piezo1 Ion Channels')
    titles.append('Planaria')
    titles.append('Plant Biology')
    titles.append('Plant Cytokinesis')
    titles.append('Plant Disease')
    titles.append('Plant Evolution')
    titles.append('Plant reproduction')
    titles.append('Plant-virus Interactions')
    titles.append('Point Of View')
    titles.append('Point of view')
    titles.append('Pollination')
    titles.append('Population Biology')
    titles.append('Prediction error')
    titles.append('Progenitor cells')
    titles.append('Prostate Cancer')
    titles.append('Proteasomes')
    titles.append('Protein Crystallography')
    titles.append('Protein Evolution')
    titles.append('Protein Folding')
    titles.append('Protein Kinases')
    titles.append('Protein Structure')
    titles.append('Protein tagging')
    titles.append('Proteomics')
    titles.append('Psychophysics')
    titles.append('Quiescence')
    titles.append('RNA Biology')
    titles.append('RNA Splicing')
    titles.append('RNA and Protein Granules')
    titles.append('RNA localization')
    titles.append('Rab GTPases')
    titles.append('Receptor Signaling')
    titles.append('Regeneration')
    titles.append('Regulatory Evolution')
    titles.append('Regulatory Proteins')
    titles.append('Reproducibility Project: Cancer Biology')
    titles.append('Reproducibility in cancer biology')
    titles.append('Reproduction')
    titles.append('Research')
    titles.append('Resource competition')
    titles.append('Retinoblastoma Protein')
    titles.append('Rev Protein')
    titles.append('Rhythmogenic Networks')
    titles.append('Science Forum')
    titles.append('Science Policy')
    titles.append('Science Writing Competition')
    titles.append('Scientific Publishing')
    titles.append('Scientific publishing')
    titles.append('Self-renewal')
    titles.append('Sensorimotor transformation')
    titles.append('Serial Behaviour')
    titles.append('Serotonin')
    titles.append('Sex Differences')
    titles.append('Signalling')
    titles.append('Single-Molecule Biophysics')
    titles.append('Skeletal stem cells')
    titles.append('Sleep')
    titles.append('Social Chemosignaling')
    titles.append('Social evolution')
    titles.append('Social networks')
    titles.append('Sperm Competition')
    titles.append('Stem Cells')
    titles.append('Stem cells')
    titles.append('Structural Biology')
    titles.append('Symbiosis')
    titles.append('Synaptic Plasticity')
    titles.append('Synthetic Biology')
    titles.append('TOR signaling')
    titles.append('The Natural History Of Model Organisms')
    titles.append('Thermotaxis')
    titles.append('Tissue Engineering')
    titles.append('Toll-like Receptors')
    titles.append('Transcription')
    titles.append('Transcriptomics')
    titles.append('Translational Oncology')
    titles.append('Transport Proteins')
    titles.append('Trisomy 21')
    titles.append('Trypanosomiasis')
    titles.append('Tuberculosis')
    titles.append('Tumor angiogenesis')
    titles.append('Tutorial')
    titles.append('Ubiquitylation')
    titles.append('Unfolded protein response')
    titles.append('Usher Proteins')
    titles.append('Vesicle Coat Proteins')
    titles.append('Virology')
    titles.append('Viruses')
    titles.append('Visual behavior')
    titles.append('mRNA decay')
    titles.append('p53 Family proteins')

    for title in titles:
        print title, ",", utils.title_case(title)



if __name__ == '__main__':
    main()
