# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'linkselect.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LinkSelect(object):
    def setupUi(self, LinkSelect):
        LinkSelect.setObjectName("LinkSelect")
        LinkSelect.resize(640, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LinkSelect.sizePolicy().hasHeightForWidth())
        LinkSelect.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(LinkSelect)
        self.verticalLayout.setObjectName("verticalLayout")
        self.group_current_corpus = QtWidgets.QGroupBox(LinkSelect)
        self.group_current_corpus.setObjectName("group_current_corpus")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.group_current_corpus)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tree_resource = CoqResourceTree(self.group_current_corpus)
        self.tree_resource.setObjectName("tree_resource")
        self.tree_resource.headerItem().setText(0, "1")
        self.gridLayout_2.addWidget(self.tree_resource, 0, 1, 1, 1)
        self.label_from_corpus = QtWidgets.QLabel(self.group_current_corpus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_from_corpus.sizePolicy().hasHeightForWidth())
        self.label_from_corpus.setSizePolicy(sizePolicy)
        self.label_from_corpus.setObjectName("label_from_corpus")
        self.gridLayout_2.addWidget(self.label_from_corpus, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.verticalLayout.addWidget(self.group_current_corpus)
        self.group_external_corpus = QtWidgets.QGroupBox(LinkSelect)
        self.group_external_corpus.setObjectName("group_external_corpus")
        self.gridLayout = QtWidgets.QGridLayout(self.group_external_corpus)
        self.gridLayout.setObjectName("gridLayout")
        self.tree_external = CoqResourceTree(self.group_external_corpus)
        self.tree_external.setObjectName("tree_external")
        self.tree_external.headerItem().setText(0, "1")
        self.gridLayout.addWidget(self.tree_external, 2, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.combo_corpus = QtWidgets.QComboBox(self.group_external_corpus)
        self.combo_corpus.setObjectName("combo_corpus")
        self.verticalLayout_2.addWidget(self.combo_corpus)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout_2, 2, 0, 1, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.verticalLayout.addWidget(self.group_external_corpus)
        self.widget_link_info = QtWidgets.QWidget(LinkSelect)
        self.widget_link_info.setObjectName("widget_link_info")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_link_info)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_from = QtWidgets.QLabel(self.widget_link_info)
        self.label_from.setObjectName("label_from")
        self.horizontalLayout_2.addWidget(self.label_from)
        self.label_4 = QtWidgets.QLabel(self.widget_link_info)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.label_to = QtWidgets.QLabel(self.widget_link_info)
        self.label_to.setObjectName("label_to")
        self.horizontalLayout_2.addWidget(self.label_to)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.label_explain = QtWidgets.QLabel(self.widget_link_info)
        self.label_explain.setWordWrap(True)
        self.label_explain.setObjectName("label_explain")
        self.verticalLayout_3.addWidget(self.label_explain)
        self.verticalLayout.addWidget(self.widget_link_info)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox = QtWidgets.QCheckBox(LinkSelect)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.buttonBox = QtWidgets.QDialogButtonBox(LinkSelect)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(LinkSelect)
        self.buttonBox.accepted.connect(LinkSelect.accept)
        self.buttonBox.rejected.connect(LinkSelect.reject)
        QtCore.QMetaObject.connectSlotsByName(LinkSelect)

    def retranslateUi(self, LinkSelect):
        _translate = QtCore.QCoreApplication.translate
        LinkSelect.setWindowTitle(_translate("LinkSelect", "Select link column – Coquery"))
        self.group_current_corpus.setTitle(_translate("LinkSelect", "&Current corpus"))
        self.label_from_corpus.setText(_translate("LinkSelect", "<html><head/><body><p><span style=\" font-weight:600;\">{from_res}</span></p></body></html>"))
        self.group_external_corpus.setTitle(_translate("LinkSelect", "E&xternal corpus"))
        self.label_from.setText(_translate("LinkSelect", "<html><head/><body><p><span style=\" font-weight:600;\">{from_table}.{from_resource}</span></p></body></html>"))
        self.label_4.setText(_translate("LinkSelect", "will be linked to"))
        self.label_to.setText(_translate("LinkSelect", "<html><head/><body><p><span style=\" font-weight:600;\">{to}.{to_table}.{to_resource}</span></p></body></html>"))
        self.label_explain.setText(_translate("LinkSelect", "The remaining columns from {to}.{to_table} will be available as output columns."))
        self.checkBox.setText(_translate("LinkSelect", "Ignore case when comparing contents."))

from ..resourcetree import CoqResourceTree

