# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rst/vision/SimpleXYZImageCollection.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import rst.vision.SimpleXYZImage_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rst/vision/SimpleXYZImageCollection.proto',
  package='rst.vision',
  serialized_pb='\n)rst/vision/SimpleXYZImageCollection.proto\x12\nrst.vision\x1a\x1frst/vision/SimpleXYZImage.proto\"G\n\x18SimpleXYZImageCollection\x12+\n\x07\x65lement\x18\x01 \x03(\x0b\x32\x1a.rst.vision.SimpleXYZImageB\x1e\x42\x1cSimpleXYZImageCollectionType')




_SIMPLEXYZIMAGECOLLECTION = _descriptor.Descriptor(
  name='SimpleXYZImageCollection',
  full_name='rst.vision.SimpleXYZImageCollection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='element', full_name='rst.vision.SimpleXYZImageCollection.element', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=90,
  serialized_end=161,
)

_SIMPLEXYZIMAGECOLLECTION.fields_by_name['element'].message_type = rst.vision.SimpleXYZImage_pb2._SIMPLEXYZIMAGE
DESCRIPTOR.message_types_by_name['SimpleXYZImageCollection'] = _SIMPLEXYZIMAGECOLLECTION

class SimpleXYZImageCollection(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SIMPLEXYZIMAGECOLLECTION

  # @@protoc_insertion_point(class_scope:rst.vision.SimpleXYZImageCollection)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'B\034SimpleXYZImageCollectionType')
# @@protoc_insertion_point(module_scope)
