
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "74a87f1c984a2ae2e27479612b6d2b217da9c533",
 "version": "1.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
