# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connectionConfiguration.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ConnectionConfig(object):
    def setupUi(self, ConnectionConfig):
        ConnectionConfig.setObjectName("ConnectionConfig")
        ConnectionConfig.resize(532, 593)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(ConnectionConfig)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_5 = QtWidgets.QLabel(ConnectionConfig)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_12.addWidget(self.label_5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(8)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tree_configuration = QtWidgets.QTreeWidget(ConnectionConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tree_configuration.sizePolicy().hasHeightForWidth())
        self.tree_configuration.setSizePolicy(sizePolicy)
        self.tree_configuration.setRootIsDecorated(False)
        self.tree_configuration.setItemsExpandable(False)
        self.tree_configuration.setHeaderHidden(True)
        self.tree_configuration.setExpandsOnDoubleClick(False)
        self.tree_configuration.setObjectName("tree_configuration")
        self.tree_configuration.headerItem().setText(0, "1")
        self.verticalLayout_4.addWidget(self.tree_configuration)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setHorizontalSpacing(8)
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.button_add = QtWidgets.QPushButton(ConnectionConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_add.sizePolicy().hasHeightForWidth())
        self.button_add.setSizePolicy(sizePolicy)
        self.button_add.setObjectName("button_add")
        self.gridLayout_3.addWidget(self.button_add, 0, 0, 1, 1)
        self.button_replace = QtWidgets.QPushButton(ConnectionConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_replace.sizePolicy().hasHeightForWidth())
        self.button_replace.setSizePolicy(sizePolicy)
        self.button_replace.setObjectName("button_replace")
        self.gridLayout_3.addWidget(self.button_replace, 0, 1, 1, 1)
        self.button_remove = QtWidgets.QPushButton(ConnectionConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_remove.sizePolicy().hasHeightForWidth())
        self.button_remove.setSizePolicy(sizePolicy)
        self.button_remove.setObjectName("button_remove")
        self.gridLayout_3.addWidget(self.button_remove, 0, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setSpacing(8)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.groupBox_2 = QtWidgets.QGroupBox(ConnectionConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.configuration_name = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.configuration_name.sizePolicy().hasHeightForWidth())
        self.configuration_name.setSizePolicy(sizePolicy)
        self.configuration_name.setObjectName("configuration_name")
        self.gridLayout_4.addWidget(self.configuration_name, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radio_mysql = QtWidgets.QRadioButton(self.groupBox_2)
        self.radio_mysql.setObjectName("radio_mysql")
        self.horizontalLayout_2.addWidget(self.radio_mysql)
        self.radio_sqlite = QtWidgets.QRadioButton(self.groupBox_2)
        self.radio_sqlite.setChecked(True)
        self.radio_sqlite.setObjectName("radio_sqlite")
        self.horizontalLayout_2.addWidget(self.radio_sqlite)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 1, 0, 1, 1)
        self.verticalLayout_11.addWidget(self.groupBox_2)
        self.frame_settings = QtWidgets.QFrame(ConnectionConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_settings.sizePolicy().hasHeightForWidth())
        self.frame_settings.setSizePolicy(sizePolicy)
        self.frame_settings.setObjectName("frame_settings")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_settings)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_mysql = QtWidgets.QWidget(self.frame_settings)
        self.frame_mysql.setObjectName("frame_mysql")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_mysql)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(8)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.frame_mysql)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setContentsMargins(-1, 10, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radio_local = QtWidgets.QRadioButton(self.groupBox)
        self.radio_local.setChecked(True)
        self.radio_local.setObjectName("radio_local")
        self.verticalLayout.addWidget(self.radio_local)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.radio_remote = QtWidgets.QRadioButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_remote.sizePolicy().hasHeightForWidth())
        self.radio_remote.setSizePolicy(sizePolicy)
        self.radio_remote.setObjectName("radio_remote")
        self.gridLayout_2.addWidget(self.radio_remote, 0, 0, 1, 1)
        self.hostname = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hostname.sizePolicy().hasHeightForWidth())
        self.hostname.setSizePolicy(sizePolicy)
        self.hostname.setInputMask("")
        self.hostname.setText("")
        self.hostname.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.hostname.setObjectName("hostname")
        self.gridLayout_2.addWidget(self.hostname, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.port = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.port.sizePolicy().hasHeightForWidth())
        self.port.setSizePolicy(sizePolicy)
        self.port.setMinimum(1)
        self.port.setMaximum(65535)
        self.port.setProperty("value", 3306)
        self.port.setObjectName("port")
        self.horizontalLayout_3.addWidget(self.port)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.group_credentials = QtWidgets.QGroupBox(self.frame_mysql)
        self.group_credentials.setObjectName("group_credentials")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.group_credentials)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.password = QtWidgets.QLineEdit(self.group_credentials)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password.sizePolicy().hasHeightForWidth())
        self.password.setSizePolicy(sizePolicy)
        self.password.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.group_credentials)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.button_create_user = QtWidgets.QPushButton(self.group_credentials)
        self.button_create_user.setObjectName("button_create_user")
        self.gridLayout.addWidget(self.button_create_user, 0, 2, 1, 1)
        self.user = QtWidgets.QLineEdit(self.group_credentials)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user.sizePolicy().hasHeightForWidth())
        self.user.setSizePolicy(sizePolicy)
        self.user.setObjectName("user")
        self.gridLayout.addWidget(self.user, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.group_credentials)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout)
        self.verticalLayout_2.addWidget(self.group_credentials)
        self.connection_indicator = QtWidgets.QFrame(self.frame_mysql)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connection_indicator.sizePolicy().hasHeightForWidth())
        self.connection_indicator.setSizePolicy(sizePolicy)
        self.connection_indicator.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.connection_indicator.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.connection_indicator.setObjectName("connection_indicator")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.connection_indicator)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.connection_indicator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.button_status = QtWidgets.QPushButton(self.connection_indicator)
        self.button_status.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_status.sizePolicy().hasHeightForWidth())
        self.button_status.setSizePolicy(sizePolicy)
        self.button_status.setText("")
        self.button_status.setAutoDefault(False)
        self.button_status.setFlat(False)
        self.button_status.setObjectName("button_status")
        self.horizontalLayout.addWidget(self.button_status)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.scrollArea = QtWidgets.QScrollArea(self.connection_indicator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 238, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_connection = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_connection.sizePolicy().hasHeightForWidth())
        self.label_connection.setSizePolicy(sizePolicy)
        self.label_connection.setText("")
        self.label_connection.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_connection.setWordWrap(True)
        self.label_connection.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_connection.setObjectName("label_connection")
        self.verticalLayout_8.addWidget(self.label_connection)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_7.addWidget(self.scrollArea)
        self.verticalLayout_9.addLayout(self.verticalLayout_7)
        self.verticalLayout_2.addWidget(self.connection_indicator)
        self.verticalLayout_5.addWidget(self.frame_mysql)
        self.frame_sqlite = QtWidgets.QGroupBox(self.frame_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_sqlite.sizePolicy().hasHeightForWidth())
        self.frame_sqlite.setSizePolicy(sizePolicy)
        self.frame_sqlite.setObjectName("frame_sqlite")
        self.sqlite_layout = QtWidgets.QVBoxLayout(self.frame_sqlite)
        self.sqlite_layout.setObjectName("sqlite_layout")
        self.checkbox_layout = QtWidgets.QHBoxLayout()
        self.checkbox_layout.setObjectName("checkbox_layout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_checkbox = QtWidgets.QLabel(self.frame_sqlite)
        self.label_checkbox.setObjectName("label_checkbox")
        self.horizontalLayout_6.addWidget(self.label_checkbox)
        self.radio_default_path = QtWidgets.QRadioButton(self.frame_sqlite)
        self.radio_default_path.setChecked(True)
        self.radio_default_path.setObjectName("radio_default_path")
        self.horizontalLayout_6.addWidget(self.radio_default_path)
        self.radio_custom_path = QtWidgets.QRadioButton(self.frame_sqlite)
        self.radio_custom_path.setChecked(False)
        self.radio_custom_path.setObjectName("radio_custom_path")
        self.horizontalLayout_6.addWidget(self.radio_custom_path)
        self.checkbox_layout.addLayout(self.horizontalLayout_6)
        self.sqlite_layout.addLayout(self.checkbox_layout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.input_db_path = QtWidgets.QLineEdit(self.frame_sqlite)
        self.input_db_path.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_db_path.sizePolicy().hasHeightForWidth())
        self.input_db_path.setSizePolicy(sizePolicy)
        self.input_db_path.setPlaceholderText("")
        self.input_db_path.setObjectName("input_db_path")
        self.horizontalLayout_4.addWidget(self.input_db_path)
        self.button_db_path = QtWidgets.QPushButton(self.frame_sqlite)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_db_path.sizePolicy().hasHeightForWidth())
        self.button_db_path.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("folder")
        self.button_db_path.setIcon(icon)
        self.button_db_path.setObjectName("button_db_path")
        self.horizontalLayout_4.addWidget(self.button_db_path)
        self.sqlite_layout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_5.addWidget(self.frame_sqlite)
        spacerItem = QtWidgets.QSpacerItem(251, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem)
        self.verticalLayout_11.addWidget(self.frame_settings)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem1)
        self.horizontalLayout_5.addLayout(self.verticalLayout_11)
        self.verticalLayout_12.addLayout(self.horizontalLayout_5)
        self.buttonBox = QtWidgets.QDialogButtonBox(ConnectionConfig)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_12.addWidget(self.buttonBox)
        self.label_5.setBuddy(self.tree_configuration)
        self.label_3.setBuddy(self.configuration_name)
        self.label_4.setBuddy(self.port)
        self.label.setBuddy(self.user)
        self.label_2.setBuddy(self.password)

        self.retranslateUi(ConnectionConfig)
        self.buttonBox.accepted.connect(ConnectionConfig.accept)
        self.buttonBox.rejected.connect(ConnectionConfig.reject)
        QtCore.QMetaObject.connectSlotsByName(ConnectionConfig)
        ConnectionConfig.setTabOrder(self.button_add, self.button_replace)
        ConnectionConfig.setTabOrder(self.button_replace, self.button_remove)
        ConnectionConfig.setTabOrder(self.button_remove, self.buttonBox)
        ConnectionConfig.setTabOrder(self.buttonBox, self.tree_configuration)

    def retranslateUi(self, ConnectionConfig):
        _translate = QtCore.QCoreApplication.translate
        ConnectionConfig.setWindowTitle(_translate("ConnectionConfig", "Database connections – Coquery"))
        self.label_5.setText(_translate("ConnectionConfig", "<html><head/><body><p><span style=\" font-weight:600;\">Database connections</span></p>"))
        self.button_add.setText(_translate("ConnectionConfig", "A&dd"))
        self.button_replace.setText(_translate("ConnectionConfig", "Replace"))
        self.button_remove.setText(_translate("ConnectionConfig", "Re&move"))
        self.label_3.setText(_translate("ConnectionConfig", "Connection &name:"))
        self.configuration_name.setText(_translate("ConnectionConfig", "Default"))
        self.radio_mysql.setText(_translate("ConnectionConfig", "&Yes"))
        self.radio_sqlite.setText(_translate("ConnectionConfig", "&No"))
        self.label_7.setText(_translate("ConnectionConfig", "Use MySQL server:"))
        self.groupBox.setTitle(_translate("ConnectionConfig", "Server location"))
        self.radio_local.setText(_translate("ConnectionConfig", "&Local server on this computer"))
        self.radio_remote.setText(_translate("ConnectionConfig", "URL or IP address:"))
        self.hostname.setPlaceholderText(_translate("ConnectionConfig", "(URL or IP address)"))
        self.label_4.setText(_translate("ConnectionConfig", "&Port number:"))
        self.group_credentials.setTitle(_translate("ConnectionConfig", "User credentials"))
        self.password.setText(_translate("ConnectionConfig", "coquery"))
        self.label.setText(_translate("ConnectionConfig", "&User name:"))
        self.button_create_user.setText(_translate("ConnectionConfig", "&Create user"))
        self.user.setText(_translate("ConnectionConfig", "coquery"))
        self.label_2.setText(_translate("ConnectionConfig", "Pass&word:"))
        self.label_6.setText(_translate("ConnectionConfig", "Connection status:"))
        self.frame_sqlite.setTitle(_translate("ConnectionConfig", "&Database directory:"))
        self.label_checkbox.setText(_translate("ConnectionConfig", "Use default directory:"))
        self.radio_default_path.setText(_translate("ConnectionConfig", "Yes"))
        self.radio_custom_path.setText(_translate("ConnectionConfig", "No"))
        self.button_db_path.setText(_translate("ConnectionConfig", "&Browse"))
        self.button_db_path.setShortcut(_translate("ConnectionConfig", "Alt+B"))


