from ...tl.mtproto_request import MTProtoRequest


class InputPeerNotifyEventsAll(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    inputPeerNotifyEventsAll#e86a2c74  = InputPeerNotifyEvents"""

    # Telegram's constructor ID (and unique identifier) for this class
    constructor_id = 0xe86a2c74

    def __init__(self):
        super().__init__()

    def on_send(self, writer):
        writer.write_int(InputPeerNotifyEventsAll.constructor_id, signed=False)

    @staticmethod
    def empty():
        """Returns an "empty" instance (all attributes are None)"""
        return InputPeerNotifyEventsAll()

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'inputPeerNotifyEventsAll#e86a2c74  = InputPeerNotifyEvents'

    def __str__(self):
        return '(inputPeerNotifyEventsAll (ID: 0xe86a2c74) = ())'.format()
