from ...tl.mtproto_request import MTProtoRequest


class UserStatusEmpty(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    userStatusEmpty#09d05049  = UserStatus"""

    # Telegram's constructor ID (and unique identifier) for this class
    constructor_id = 0x9d05049

    def __init__(self):
        super().__init__()

    def on_send(self, writer):
        writer.write_int(UserStatusEmpty.constructor_id, signed=False)

    @staticmethod
    def empty():
        """Returns an "empty" instance (all attributes are None)"""
        return UserStatusEmpty()

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'userStatusEmpty#09d05049  = UserStatus'

    def __str__(self):
        return '(userStatusEmpty (ID: 0x9d05049) = ())'.format()
