from ....tl.mtproto_request import MTProtoRequest


class GetAllDraftsRequest(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    messages.getAllDrafts#6a3f8d65  = Updates"""

    # Telegram's constructor ID (and unique identifier) for this class
    constructor_id = 0x6a3f8d65

    def __init__(self):
        super().__init__()
        self.result = None
        self.confirmed = True  # Confirmed by default

    def on_send(self, writer):
        writer.write_int(GetAllDraftsRequest.constructor_id, signed=False)

    @staticmethod
    def empty():
        """Returns an "empty" instance (all attributes are None)"""
        return GetAllDraftsRequest()

    def on_response(self, reader):
        self.result = reader.tgread_object()

    def __repr__(self):
        return 'messages.getAllDrafts#6a3f8d65  = Updates'

    def __str__(self):
        return '(messages.getAllDrafts (ID: 0x6a3f8d65) = ())'.format()
