
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-05-05T12:15:48+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "7dc11bb428ff3c9dc8a660e1299492d981c5c156",
 "version": "2.0.0a4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
