from ....tl.mtproto_request import MTProtoRequest


class GetAuthorizationsRequest(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    account.getAuthorizations#e320c158  = account.Authorizations"""

    # Telegram's constructor ID (and unique identifier) for this class
    constructor_id = 0xe320c158

    def __init__(self):
        super().__init__()
        self.result = None
        self.confirmed = True  # Confirmed by default

    def on_send(self, writer):
        writer.write_int(GetAuthorizationsRequest.constructor_id, signed=False)

    @staticmethod
    def empty():
        """Returns an "empty" instance (all attributes are None)"""
        return GetAuthorizationsRequest()

    def on_response(self, reader):
        self.result = reader.tgread_object()

    def __repr__(self):
        return 'account.getAuthorizations#e320c158  = account.Authorizations'

    def __str__(self):
        return '(account.getAuthorizations (ID: 0xe320c158) = ())'.format()
