# -*- coding: utf-8 -*-


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Ui_Settings(object):
    def setupUi(self, Ui_Settings):
        Ui_Settings.setObjectName("Ui_Settings")
        Ui_Settings.setWindowModality(QtCore.Qt.ApplicationModal)
        Ui_Settings.resize(792, 774)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/hammer"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Ui_Settings.setWindowIcon(icon)
        Ui_Settings.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayout = QtWidgets.QVBoxLayout(Ui_Settings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.settingsTab = QtWidgets.QTabWidget(Ui_Settings)
        self.settingsTab.setObjectName("settingsTab")
        self.tabDetector = QtWidgets.QWidget()
        self.tabDetector.setObjectName("tabDetector")
        self.formLayout = QtWidgets.QFormLayout(self.tabDetector)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.tabDetector)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.editDetAddress = QtWidgets.QLineEdit(self.tabDetector)
        self.editDetAddress.setObjectName("editDetAddress")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.editDetAddress)
        self.label_2 = QtWidgets.QLabel(self.tabDetector)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.editReadout1 = QtWidgets.QLineEdit(self.tabDetector)
        self.editReadout1.setObjectName("editReadout1")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.editReadout1)
        self.label_3 = QtWidgets.QLabel(self.tabDetector)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.editReadout2 = QtWidgets.QLineEdit(self.tabDetector)
        self.editReadout2.setObjectName("editReadout2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.editReadout2)
        self.label_4 = QtWidgets.QLabel(self.tabDetector)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.editSeparator = QtWidgets.QLineEdit(self.tabDetector)
        self.editSeparator.setObjectName("editSeparator")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.editSeparator)
        self.label_5 = QtWidgets.QLabel(self.tabDetector)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.editServerDir = QtWidgets.QLineEdit(self.tabDetector)
        self.editServerDir.setObjectName("editServerDir")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.editServerDir)
        self.editLogFile = QtWidgets.QLineEdit(self.tabDetector)
        self.editLogFile.setObjectName("editLogFile")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.editLogFile)
        self.label_6 = QtWidgets.QLabel(self.tabDetector)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.settingsTab.addTab(self.tabDetector, "")
        self.tabDiffractometer = QtWidgets.QWidget()
        self.tabDiffractometer.setObjectName("tabDiffractometer")
        self.formLayout_3 = QtWidgets.QFormLayout(self.tabDiffractometer)
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_11 = QtWidgets.QLabel(self.tabDiffractometer)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.editUserDir = QtWidgets.QLineEdit(self.tabDiffractometer)
        self.editUserDir.setObjectName("editUserDir")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.editUserDir)
        self.label_12 = QtWidgets.QLabel(self.tabDiffractometer)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.editDataDir = QtWidgets.QLineEdit(self.tabDiffractometer)
        self.editDataDir.setText("")
        self.editDataDir.setObjectName("editDataDir")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.editDataDir)
        self.label_13 = QtWidgets.QLabel(self.tabDiffractometer)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.editNoBeamCounts = QtWidgets.QLineEdit(self.tabDiffractometer)
        self.editNoBeamCounts.setText("")
        self.editNoBeamCounts.setObjectName("editNoBeamCounts")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.editNoBeamCounts)
        self.label_14 = QtWidgets.QLabel(self.tabDiffractometer)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.editMonitorSpec = QtWidgets.QLineEdit(self.tabDiffractometer)
        self.editMonitorSpec.setText("")
        self.editMonitorSpec.setObjectName("editMonitorSpec")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.editMonitorSpec)
        self.label_15 = QtWidgets.QLabel(self.tabDiffractometer)
        self.label_15.setObjectName("label_15")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.editMusstSpec = QtWidgets.QLineEdit(self.tabDiffractometer)
        self.editMusstSpec.setText("")
        self.editMusstSpec.setObjectName("editMusstSpec")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.editMusstSpec)
        self.label_16 = QtWidgets.QLabel(self.tabDiffractometer)
        self.label_16.setObjectName("label_16")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.editMusstTimeout1 = QtWidgets.QLineEdit(self.tabDiffractometer)
        self.editMusstTimeout1.setText("")
        self.editMusstTimeout1.setObjectName("editMusstTimeout1")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.editMusstTimeout1)
        self.label_17 = QtWidgets.QLabel(self.tabDiffractometer)
        self.label_17.setObjectName("label_17")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.editMusstTimeout2 = QtWidgets.QLineEdit(self.tabDiffractometer)
        self.editMusstTimeout2.setText("")
        self.editMusstTimeout2.setObjectName("editMusstTimeout2")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.editMusstTimeout2)
        self.label_40 = QtWidgets.QLabel(self.tabDiffractometer)
        self.label_40.setObjectName("label_40")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_40)
        self.editMusstFirmware = QtWidgets.QLineEdit(self.tabDiffractometer)
        self.editMusstFirmware.setText("")
        self.editMusstFirmware.setObjectName("editMusstFirmware")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.editMusstFirmware)
        self.label_37 = QtWidgets.QLabel(self.tabDiffractometer)
        self.label_37.setObjectName("label_37")
        self.formLayout_3.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_37)
        self.editNumberOfFilters = QtWidgets.QLineEdit(self.tabDiffractometer)
        self.editNumberOfFilters.setText("")
        self.editNumberOfFilters.setObjectName("editNumberOfFilters")
        self.formLayout_3.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.editNumberOfFilters)
        self.label_39 = QtWidgets.QLabel(self.tabDiffractometer)
        self.label_39.setObjectName("label_39")
        self.formLayout_3.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_39)
        self.editBeamstopOn = QtWidgets.QLineEdit(self.tabDiffractometer)
        self.editBeamstopOn.setText("")
        self.editBeamstopOn.setObjectName("editBeamstopOn")
        self.formLayout_3.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.editBeamstopOn)
        self.label_38 = QtWidgets.QLabel(self.tabDiffractometer)
        self.label_38.setObjectName("label_38")
        self.formLayout_3.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_38)
        self.editBeamstopOff = QtWidgets.QLineEdit(self.tabDiffractometer)
        self.editBeamstopOff.setText("")
        self.editBeamstopOff.setObjectName("editBeamstopOff")
        self.formLayout_3.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.editBeamstopOff)
        self.label_42 = QtWidgets.QLabel(self.tabDiffractometer)
        self.label_42.setObjectName("label_42")
        self.formLayout_3.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.label_42)
        self.editRootHash = QtWidgets.QLineEdit(self.tabDiffractometer)
        self.editRootHash.setText("")
        self.editRootHash.setObjectName("editRootHash")
        self.formLayout_3.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.editRootHash)
        self.editCommTimeout = QtWidgets.QLineEdit(self.tabDiffractometer)
        self.editCommTimeout.setText("")
        self.editCommTimeout.setObjectName("editCommTimeout")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.editCommTimeout)
        self.label_41 = QtWidgets.QLabel(self.tabDiffractometer)
        self.label_41.setObjectName("label_41")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_41)
        self.settingsTab.addTab(self.tabDiffractometer, "")
        self.tabMotors = QtWidgets.QWidget()
        self.tabMotors.setObjectName("tabMotors")
        self.formLayout_4 = QtWidgets.QFormLayout(self.tabMotors)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_20 = QtWidgets.QLabel(self.tabMotors)
        self.label_20.setObjectName("label_20")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.editMono = QtWidgets.QLineEdit(self.tabMotors)
        self.editMono.setObjectName("editMono")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.editMono)
        self.label_22 = QtWidgets.QLabel(self.tabMotors)
        self.label_22.setObjectName("label_22")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.editPhi = QtWidgets.QLineEdit(self.tabMotors)
        self.editPhi.setText("")
        self.editPhi.setObjectName("editPhi")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.editPhi)
        self.label_23 = QtWidgets.QLabel(self.tabMotors)
        self.label_23.setObjectName("label_23")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.editPrphi = QtWidgets.QLineEdit(self.tabMotors)
        self.editPrphi.setText("")
        self.editPrphi.setObjectName("editPrphi")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.editPrphi)
        self.label_21 = QtWidgets.QLabel(self.tabMotors)
        self.label_21.setObjectName("label_21")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.editOmega = QtWidgets.QLineEdit(self.tabMotors)
        self.editOmega.setText("")
        self.editOmega.setObjectName("editOmega")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.editOmega)
        self.label_18 = QtWidgets.QLabel(self.tabMotors)
        self.label_18.setObjectName("label_18")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.editBstop = QtWidgets.QLineEdit(self.tabMotors)
        self.editBstop.setText("")
        self.editBstop.setObjectName("editBstop")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.editBstop)
        self.label_24 = QtWidgets.QLabel(self.tabMotors)
        self.label_24.setObjectName("label_24")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.editPldistf = QtWidgets.QLineEdit(self.tabMotors)
        self.editPldistf.setText("")
        self.editPldistf.setObjectName("editPldistf")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.editPldistf)
        self.label_19 = QtWidgets.QLabel(self.tabMotors)
        self.label_19.setObjectName("label_19")
        self.formLayout_4.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.editPldistd = QtWidgets.QLineEdit(self.tabMotors)
        self.editPldistd.setText("")
        self.editPldistd.setObjectName("editPldistd")
        self.formLayout_4.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.editPldistd)
        self.label_32 = QtWidgets.QLabel(self.tabMotors)
        self.label_32.setObjectName("label_32")
        self.formLayout_4.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.editPlvert = QtWidgets.QLineEdit(self.tabMotors)
        self.editPlvert.setObjectName("editPlvert")
        self.formLayout_4.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.editPlvert)
        self.label_34 = QtWidgets.QLabel(self.tabMotors)
        self.label_34.setObjectName("label_34")
        self.formLayout_4.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.editPlrot = QtWidgets.QLineEdit(self.tabMotors)
        self.editPlrot.setText("")
        self.editPlrot.setObjectName("editPlrot")
        self.formLayout_4.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.editPlrot)
        self.label_33 = QtWidgets.QLabel(self.tabMotors)
        self.label_33.setObjectName("label_33")
        self.formLayout_4.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.editPrver = QtWidgets.QLineEdit(self.tabMotors)
        self.editPrver.setText("")
        self.editPrver.setObjectName("editPrver")
        self.formLayout_4.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.editPrver)
        self.label_35 = QtWidgets.QLabel(self.tabMotors)
        self.label_35.setObjectName("label_35")
        self.formLayout_4.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.editPrhor = QtWidgets.QLineEdit(self.tabMotors)
        self.editPrhor.setText("")
        self.editPrhor.setObjectName("editPrhor")
        self.formLayout_4.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.editPrhor)
        self.label_36 = QtWidgets.QLabel(self.tabMotors)
        self.label_36.setObjectName("label_36")
        self.formLayout_4.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.label_36)
        self.editFilter = QtWidgets.QLineEdit(self.tabMotors)
        self.editFilter.setText("")
        self.editFilter.setObjectName("editFilter")
        self.formLayout_4.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.editFilter)
        self.editKappa = QtWidgets.QLineEdit(self.tabMotors)
        self.editKappa.setText("")
        self.editKappa.setObjectName("editKappa")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.editKappa)
        self.label_26 = QtWidgets.QLabel(self.tabMotors)
        self.label_26.setObjectName("label_26")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.settingsTab.addTab(self.tabMotors, "")
        self.tabScan = QtWidgets.QWidget()
        self.tabScan.setObjectName("tabScan")
        self.formLayout_5 = QtWidgets.QFormLayout(self.tabScan)
        self.formLayout_5.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_27 = QtWidgets.QLabel(self.tabScan)
        self.label_27.setObjectName("label_27")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.editScanAxis = QtWidgets.QLineEdit(self.tabScan)
        self.editScanAxis.setObjectName("editScanAxis")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.editScanAxis)
        self.label_29 = QtWidgets.QLabel(self.tabScan)
        self.label_29.setObjectName("label_29")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.editScanTime = QtWidgets.QLineEdit(self.tabScan)
        self.editScanTime.setText("")
        self.editScanTime.setObjectName("editScanTime")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.editScanTime)
        self.label_30 = QtWidgets.QLabel(self.tabScan)
        self.label_30.setObjectName("label_30")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.editScanRange = QtWidgets.QLineEdit(self.tabScan)
        self.editScanRange.setText("")
        self.editScanRange.setObjectName("editScanRange")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.editScanRange)
        self.label_28 = QtWidgets.QLabel(self.tabScan)
        self.label_28.setObjectName("label_28")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.editScanStep = QtWidgets.QLineEdit(self.tabScan)
        self.editScanStep.setText("")
        self.editScanStep.setObjectName("editScanStep")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.editScanStep)
        self.label_25 = QtWidgets.QLabel(self.tabScan)
        self.label_25.setObjectName("label_25")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.editScanFilter = QtWidgets.QLineEdit(self.tabScan)
        self.editScanFilter.setText("")
        self.editScanFilter.setObjectName("editScanFilter")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.editScanFilter)
        self.settingsTab.addTab(self.tabScan, "")
        self.verticalLayout.addWidget(self.settingsTab)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.applyButton = QtWidgets.QPushButton(Ui_Settings)
        self.applyButton.setObjectName("applyButton")
        self.horizontalLayout.addWidget(self.applyButton)
        self.cancelButton = QtWidgets.QPushButton(Ui_Settings)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Ui_Settings)
        self.settingsTab.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Ui_Settings)

    def retranslateUi(self, Ui_Settings):
        _translate = QtCore.QCoreApplication.translate
        Ui_Settings.setWindowTitle(_translate("Ui_Settings", "Pylatus settings"))
        self.label.setText(_translate("Ui_Settings", "Address"))
        self.label_2.setText(_translate("Ui_Settings", "Readout time 1"))
        self.label_3.setText(_translate("Ui_Settings", "Readout time 2"))
        self.label_4.setText(_translate("Ui_Settings", "String separator"))
        self.label_5.setText(_translate("Ui_Settings", "Server dir"))
        self.label_6.setText(_translate("Ui_Settings", "Log file"))
        self.settingsTab.setTabText(self.settingsTab.indexOf(self.tabDetector), _translate("Ui_Settings", "Detector"))
        self.label_11.setText(_translate("Ui_Settings", "User home dir"))
        self.label_12.setText(_translate("Ui_Settings", "Data home dir"))
        self.label_13.setText(_translate("Ui_Settings", "No beam counts"))
        self.label_14.setText(_translate("Ui_Settings", "Monitor SPEC"))
        self.label_15.setText(_translate("Ui_Settings", "Musst SPEC"))
        self.label_16.setText(_translate("Ui_Settings", "Musst Timeout 1"))
        self.label_17.setText(_translate("Ui_Settings", "Musst Timeout 2"))
        self.label_40.setText(_translate("Ui_Settings", "Musst firmware"))
        self.label_37.setText(_translate("Ui_Settings", "Number of filters"))
        self.label_39.setText(_translate("Ui_Settings", "Beamstop On"))
        self.label_38.setText(_translate("Ui_Settings", "Beamstop Off"))
        self.label_42.setText(_translate("Ui_Settings", "Root password hash"))
        self.label_41.setText(_translate("Ui_Settings", "Cryo/Euro timeout (msec)"))
        self.settingsTab.setTabText(self.settingsTab.indexOf(self.tabDiffractometer), _translate("Ui_Settings", "Diffractometer"))
        self.label_20.setText(_translate("Ui_Settings", "mono"))
        self.label_22.setText(_translate("Ui_Settings", "phi"))
        self.label_23.setText(_translate("Ui_Settings", "prphi"))
        self.label_21.setText(_translate("Ui_Settings", "omega"))
        self.label_18.setText(_translate("Ui_Settings", "bstop"))
        self.label_24.setText(_translate("Ui_Settings", "pldistf"))
        self.label_19.setText(_translate("Ui_Settings", "pldistd"))
        self.label_32.setText(_translate("Ui_Settings", "plvert"))
        self.label_34.setText(_translate("Ui_Settings", "plrot"))
        self.label_33.setText(_translate("Ui_Settings", "prver"))
        self.label_35.setText(_translate("Ui_Settings", "prhor"))
        self.label_36.setText(_translate("Ui_Settings", "filter"))
        self.label_26.setText(_translate("Ui_Settings", "kappa"))
        self.settingsTab.setTabText(self.settingsTab.indexOf(self.tabMotors), _translate("Ui_Settings", "Motors"))
        self.label_27.setText(_translate("Ui_Settings", "Axis"))
        self.label_29.setText(_translate("Ui_Settings", "Time"))
        self.label_30.setText(_translate("Ui_Settings", "Range"))
        self.label_28.setText(_translate("Ui_Settings", "Step"))
        self.label_25.setText(_translate("Ui_Settings", "Filter"))
        self.settingsTab.setTabText(self.settingsTab.indexOf(self.tabScan), _translate("Ui_Settings", "Autoscan"))
        self.applyButton.setText(_translate("Ui_Settings", "Apply"))
        self.cancelButton.setText(_translate("Ui_Settings", "Cancel"))

from . import resources_rc

