
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-06-05T12:16:45-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "57a5b66264132a5adba382c0d99619f68b6f239c",
 "version": "v0.5.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
