
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-05-06T03:02:05-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "507c83b767b7cc415ab8b917e1b118fc48b4a1f7",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
