
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-05-07T22:39:55-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "de1ccdca911956930d9413df67acc3ee9c64012c",
 "version": "0.1.0a1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
