import cofecms.api
from cofecms.api import CofeCMS  # noqa

__author__ = 'The Developer Society'
__email__ = 'studio@dev.ngo'
__version__ = '0.1.1'

PLACE_TYPE_ARCHDEACONRY = cofecms.api.PLACE_TYPE_ARCHDEACONRY
PLACE_TYPE_BENEFICE = cofecms.api.PLACE_TYPE_BENEFICE
PLACE_TYPE_CHURCH = cofecms.api.PLACE_TYPE_CHURCH
PLACE_TYPE_DEANERY = cofecms.api.PLACE_TYPE_DEANERY
PLACE_TYPE_DIOCESE = cofecms.api.PLACE_TYPE_DIOCESE
PLACE_TYPE_EXTRA_PAROCHIAL = cofecms.api.PLACE_TYPE_EXTRA_PAROCHIAL
PLACE_TYPE_NONPAROCHIAL = cofecms.api.PLACE_TYPE_NONPAROCHIAL
PLACE_TYPE_PARISH = cofecms.api.PLACE_TYPE_PARISH
PLACE_TYPE_SCHOOL = cofecms.api.PLACE_TYPE_SCHOOL
PLACE_TYPE_DISTRICT = cofecms.api.PLACE_TYPE_DISTRICT
PLACE_TYPE_OFFICE = cofecms.api.PLACE_TYPE_OFFICE
PLACE_TYPE_CLERGY_RESIDENCE = cofecms.api.PLACE_TYPE_CLERGY_RESIDENCE
PLACE_TYPE_GROUP = cofecms.api.PLACE_TYPE_GROUP
PLACE_TYPE_HALL = cofecms.api.PLACE_TYPE_HALL

PRIVACY_SETTING_PRIVATE = cofecms.api.PRIVACY_SETTING_PRIVATE
PRIVACY_SETTING_DIOCESE_ONLY = cofecms.api.PRIVACY_SETTING_DIOCESE_ONLY
PRIVACY_SETTING_PUBLIC = cofecms.api.PRIVACY_SETTING_PUBLIC
