
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "77d0b3376544f469e38dfdbad747b79d147bf8f0",
 "version": "1.1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
