# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rst/dynamics/MotorCurrentsCollection.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import rst.dynamics.MotorCurrents_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rst/dynamics/MotorCurrentsCollection.proto',
  package='rst.dynamics',
  serialized_pb='\n*rst/dynamics/MotorCurrentsCollection.proto\x12\x0crst.dynamics\x1a rst/dynamics/MotorCurrents.proto\"G\n\x17MotorCurrentsCollection\x12,\n\x07\x65lement\x18\x01 \x03(\x0b\x32\x1b.rst.dynamics.MotorCurrentsB\x1d\x42\x1bMotorCurrentsCollectionType')




_MOTORCURRENTSCOLLECTION = _descriptor.Descriptor(
  name='MotorCurrentsCollection',
  full_name='rst.dynamics.MotorCurrentsCollection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='element', full_name='rst.dynamics.MotorCurrentsCollection.element', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=94,
  serialized_end=165,
)

_MOTORCURRENTSCOLLECTION.fields_by_name['element'].message_type = rst.dynamics.MotorCurrents_pb2._MOTORCURRENTS
DESCRIPTOR.message_types_by_name['MotorCurrentsCollection'] = _MOTORCURRENTSCOLLECTION

class MotorCurrentsCollection(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MOTORCURRENTSCOLLECTION

  # @@protoc_insertion_point(class_scope:rst.dynamics.MotorCurrentsCollection)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'B\033MotorCurrentsCollectionType')
# @@protoc_insertion_point(module_scope)
