# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-25 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrwyoauthConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oauth_to', models.CharField(choices=[('SINA', 'SINA'), ('QQ', 'QQ'), ('GITHUB', 'GITHUB')], max_length=100, verbose_name='TARGET_OAUTH')),
                ('authorize_url', models.CharField(max_length=100, verbose_name='AUTHORIZE_URL')),
                ('client_id', models.CharField(max_length=100, verbose_name='CLIENT_ID')),
                ('client_secret', models.CharField(max_length=100, verbose_name='CLIENT_SECRET')),
                ('call_back', models.CharField(max_length=100, verbose_name='CALL_BACK')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='SITE')),
            ],
            options={
                'db_table': 'crwyoauth_config',
                'verbose_name': 'CRWY_OAUTH',
                'verbose_name_plural': 'CRWY_OAUTH',
            },
        ),
        migrations.AlterUniqueTogether(
            name='crwyoauthconfig',
            unique_together=set([('oauth_to', 'site')]),
        ),
    ]
