
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-05-21T18:51:08+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9782c1ca05735f721246b646afee4f0deb5a695a",
 "version": "v1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
