# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-01 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from ..conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='IFramePlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_iframe2_iframeplugin', serialize=False, to='cms.CMSPlugin')),
                ('style', models.CharField(blank=True, choices=settings.CMSPLUGIN_IFRAME_CLASSES, help_text='value of HTML attribute class', max_length=50, null=True, verbose_name='style')),
                ('width', models.CharField(blank=True, choices=settings.CMSPLUGIN_IFRAME_WIDTHS, max_length=10, null=True, verbose_name='width')),
                ('height', models.CharField(blank=True, choices=settings.CMSPLUGIN_IFRAME_HEIGHTS, max_length=10, null=True, verbose_name='height')),
                ('align', models.CharField(blank=True, choices=[('left', 'align left'), ('right', 'align right')], max_length=10, null=True, verbose_name='align')),
                ('src', models.TextField(verbose_name='url')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
