# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlRedirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_source', models.TextField(unique=True)),
                ('url_destination', models.TextField()),
                ('date_initial_validity', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_end_validity', models.DateTimeField(default=django.utils.timezone.now)),
                ('views', models.PositiveIntegerField(default=0)),
                ('status', models.SmallIntegerField(choices=[(1, b'Active'), (2, b'Archived'), (3, b'Deleted')], default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
