XXXX XXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXXXXXXXX
         XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBB XXXXXXXXXXXXXBBBBBXX
    
    BB BBBBBBBBBBBBBBBBB XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
  XXXXXXXX
  XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBXXXXXXXBBBBBXX
    XXXXXXXXXXXXXXX
  XXXXXX
XXXXXX