XXXX XXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXXXXXXXX
         XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBB XXXXXXXXXXXXXBBBBBXX
    
    BB BBBBBBBBBBBBBBBBB XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
  XXXXXXXX
  XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
  XXXXXX
XXXXXX