XXXX XXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXXXXXXXX
         XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBB XXXXXXXXXXXXXBBBBBXX
    
    BB BBBBBBBBBBBBBBBBB XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
  XXXXXXXX
  XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
  XXXXXX
XXXXXX