# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-23 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpcanvas', '0003_auto_20170523_1339'),
        ('dpprogram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='canvas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='program', to='dpcanvas.Canvas', verbose_name='canvas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='summary',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
