from ...tl.mtproto_request import MTProtoRequest


class ChannelMessagesFilterEmpty(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    channelMessagesFilterEmpty#94d42ee7  = ChannelMessagesFilter"""

    # Telegram's constructor ID (and unique identifier) for this class
    constructor_id = 0x94d42ee7

    def __init__(self):
        super().__init__()

    def on_send(self, writer):
        writer.write_int(ChannelMessagesFilterEmpty.constructor_id, signed=False)

    @staticmethod
    def empty():
        """Returns an "empty" instance (all attributes are None)"""
        return ChannelMessagesFilterEmpty()

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'channelMessagesFilterEmpty#94d42ee7  = ChannelMessagesFilter'

    def __str__(self):
        return '(channelMessagesFilterEmpty (ID: 0x94d42ee7) = ())'.format()
