from ...tl.mtproto_request import MTProtoRequest


class InputMessagesFilterVideo(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    inputMessagesFilterVideo#9fc00e65  = MessagesFilter"""

    # Telegram's constructor ID (and unique identifier) for this class
    constructor_id = 0x9fc00e65

    def __init__(self):
        super().__init__()

    def on_send(self, writer):
        writer.write_int(InputMessagesFilterVideo.constructor_id, signed=False)

    @staticmethod
    def empty():
        """Returns an "empty" instance (all attributes are None)"""
        return InputMessagesFilterVideo()

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'inputMessagesFilterVideo#9fc00e65  = MessagesFilter'

    def __str__(self):
        return '(inputMessagesFilterVideo (ID: 0x9fc00e65) = ())'.format()
