from ...tl.mtproto_request import MTProtoRequest


class PrivacyKeyChatInvite(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    privacyKeyChatInvite#500e6dfa  = PrivacyKey"""

    # Telegram's constructor ID (and unique identifier) for this class
    constructor_id = 0x500e6dfa

    def __init__(self):
        super().__init__()

    def on_send(self, writer):
        writer.write_int(PrivacyKeyChatInvite.constructor_id, signed=False)

    @staticmethod
    def empty():
        """Returns an "empty" instance (all attributes are None)"""
        return PrivacyKeyChatInvite()

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'privacyKeyChatInvite#500e6dfa  = PrivacyKey'

    def __str__(self):
        return '(privacyKeyChatInvite (ID: 0x500e6dfa) = ())'.format()
