from ...tl.mtproto_request import MTProtoRequest


class UpdateRecentStickers(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    updateRecentStickers#9a422c20  = Update"""

    # Telegram's constructor ID (and unique identifier) for this class
    constructor_id = 0x9a422c20

    def __init__(self):
        super().__init__()

    def on_send(self, writer):
        writer.write_int(UpdateRecentStickers.constructor_id, signed=False)

    @staticmethod
    def empty():
        """Returns an "empty" instance (all attributes are None)"""
        return UpdateRecentStickers()

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'updateRecentStickers#9a422c20  = Update'

    def __str__(self):
        return '(updateRecentStickers (ID: 0x9a422c20) = ())'.format()
