# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rst/geometry/Lengths.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rst/geometry/Lengths.proto',
  package='rst.geometry',
  serialized_pb='\n\x1arst/geometry/Lengths.proto\x12\x0crst.geometry\"\x1a\n\x07Lengths\x12\x0f\n\x07lengths\x18\x01 \x03(\x01\x42\rB\x0bLengthsType')




_LENGTHS = _descriptor.Descriptor(
  name='Lengths',
  full_name='rst.geometry.Lengths',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lengths', full_name='rst.geometry.Lengths.lengths', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=44,
  serialized_end=70,
)

DESCRIPTOR.message_types_by_name['Lengths'] = _LENGTHS

class Lengths(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LENGTHS

  # @@protoc_insertion_point(class_scope:rst.geometry.Lengths)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'B\013LengthsType')
# @@protoc_insertion_point(module_scope)
