# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rst/geometry/PointCloud3DFloat.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import rst.math.Vec3DFloat_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rst/geometry/PointCloud3DFloat.proto',
  package='rst.geometry',
  serialized_pb='\n$rst/geometry/PointCloud3DFloat.proto\x12\x0crst.geometry\x1a\x19rst/math/Vec3DFloat.proto\"9\n\x11PointCloud3DFloat\x12$\n\x06points\x18\x01 \x03(\x0b\x32\x14.rst.math.Vec3DFloatB\x17\x42\x15PointCloud3DFloatType')




_POINTCLOUD3DFLOAT = _descriptor.Descriptor(
  name='PointCloud3DFloat',
  full_name='rst.geometry.PointCloud3DFloat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='rst.geometry.PointCloud3DFloat.points', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=81,
  serialized_end=138,
)

_POINTCLOUD3DFLOAT.fields_by_name['points'].message_type = rst.math.Vec3DFloat_pb2._VEC3DFLOAT
DESCRIPTOR.message_types_by_name['PointCloud3DFloat'] = _POINTCLOUD3DFLOAT

class PointCloud3DFloat(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _POINTCLOUD3DFLOAT

  # @@protoc_insertion_point(class_scope:rst.geometry.PointCloud3DFloat)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'B\025PointCloud3DFloatType')
# @@protoc_insertion_point(module_scope)
