# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rst/geometry/PointCloudSet3DFloat.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import rst.geometry.PointCloud3DFloat_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rst/geometry/PointCloudSet3DFloat.proto',
  package='rst.geometry',
  serialized_pb='\n\'rst/geometry/PointCloudSet3DFloat.proto\x12\x0crst.geometry\x1a$rst/geometry/PointCloud3DFloat.proto\"G\n\x14PointCloudSet3DFloat\x12/\n\x06\x63louds\x18\x01 \x03(\x0b\x32\x1f.rst.geometry.PointCloud3DFloatB\x1a\x42\x18PointCloudSet3DFloatType')




_POINTCLOUDSET3DFLOAT = _descriptor.Descriptor(
  name='PointCloudSet3DFloat',
  full_name='rst.geometry.PointCloudSet3DFloat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clouds', full_name='rst.geometry.PointCloudSet3DFloat.clouds', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=95,
  serialized_end=166,
)

_POINTCLOUDSET3DFLOAT.fields_by_name['clouds'].message_type = rst.geometry.PointCloud3DFloat_pb2._POINTCLOUD3DFLOAT
DESCRIPTOR.message_types_by_name['PointCloudSet3DFloat'] = _POINTCLOUDSET3DFLOAT

class PointCloudSet3DFloat(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _POINTCLOUDSET3DFLOAT

  # @@protoc_insertion_point(class_scope:rst.geometry.PointCloudSet3DFloat)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'B\030PointCloudSet3DFloatType')
# @@protoc_insertion_point(module_scope)
