from ...tl.mtproto_request import MTProtoRequest


class DocumentAttributeAnimated(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    documentAttributeAnimated#11b58939  = DocumentAttribute"""

    # Telegram's constructor ID (and unique identifier) for this class
    constructor_id = 0x11b58939

    def __init__(self):
        super().__init__()

    def on_send(self, writer):
        writer.write_int(DocumentAttributeAnimated.constructor_id, signed=False)

    @staticmethod
    def empty():
        """Returns an "empty" instance (all attributes are None)"""
        return DocumentAttributeAnimated()

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'documentAttributeAnimated#11b58939  = DocumentAttribute'

    def __str__(self):
        return '(documentAttributeAnimated (ID: 0x11b58939) = ())'.format()
