from ...tl.mtproto_request import MTProtoRequest


class InputNotifyUsers(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    inputNotifyUsers#193b4417  = InputNotifyPeer"""

    # Telegram's constructor ID (and unique identifier) for this class
    constructor_id = 0x193b4417

    def __init__(self):
        super().__init__()

    def on_send(self, writer):
        writer.write_int(InputNotifyUsers.constructor_id, signed=False)

    @staticmethod
    def empty():
        """Returns an "empty" instance (all attributes are None)"""
        return InputNotifyUsers()

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'inputNotifyUsers#193b4417  = InputNotifyPeer'

    def __str__(self):
        return '(inputNotifyUsers (ID: 0x193b4417) = ())'.format()
