from ...tl.mtproto_request import MTProtoRequest


class InputMessagesFilterMusic(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    inputMessagesFilterMusic#3751b49e  = MessagesFilter"""

    # Telegram's constructor ID (and unique identifier) for this class
    constructor_id = 0x3751b49e

    def __init__(self):
        super().__init__()

    def on_send(self, writer):
        writer.write_int(InputMessagesFilterMusic.constructor_id, signed=False)

    @staticmethod
    def empty():
        """Returns an "empty" instance (all attributes are None)"""
        return InputMessagesFilterMusic()

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'inputMessagesFilterMusic#3751b49e  = MessagesFilter'

    def __str__(self):
        return '(inputMessagesFilterMusic (ID: 0x3751b49e) = ())'.format()
