from ...tl.mtproto_request import MTProtoRequest


class NotifyUsers(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    notifyUsers#b4c83b4c  = NotifyPeer"""

    # Telegram's constructor ID (and unique identifier) for this class
    constructor_id = 0xb4c83b4c

    def __init__(self):
        super().__init__()

    def on_send(self, writer):
        writer.write_int(NotifyUsers.constructor_id, signed=False)

    @staticmethod
    def empty():
        """Returns an "empty" instance (all attributes are None)"""
        return NotifyUsers()

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'notifyUsers#b4c83b4c  = NotifyPeer'

    def __str__(self):
        return '(notifyUsers (ID: 0xb4c83b4c) = ())'.format()
