from ...tl.mtproto_request import MTProtoRequest


class SendMessageCancelAction(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    sendMessageCancelAction#fd5ec8f5  = SendMessageAction"""

    # Telegram's constructor ID (and unique identifier) for this class
    constructor_id = 0xfd5ec8f5

    def __init__(self):
        super().__init__()

    def on_send(self, writer):
        writer.write_int(SendMessageCancelAction.constructor_id, signed=False)

    @staticmethod
    def empty():
        """Returns an "empty" instance (all attributes are None)"""
        return SendMessageCancelAction()

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'sendMessageCancelAction#fd5ec8f5  = SendMessageAction'

    def __str__(self):
        return '(sendMessageCancelAction (ID: 0xfd5ec8f5) = ())'.format()
