
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-05-19T17:05:20-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "1ba7da066b6f3154951b28929b70eeb43592a12b",
 "version": "0.1.0b3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
