
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "151e585229ec16dade554b1c2ecc876164911f5e",
 "version": "0.23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
