
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.2.0'
version_full = '35323025c02f0a49716acb8d3bc140d498836620'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

