# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-23 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpcanvas', '0002_canvas_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvas',
            name='summary',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='canvas',
            name='name',
            field=models.TextField(default='one', max_length=500),
            preserve_default=False,
        ),
    ]
