# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-24 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dpcanvas', '0003_auto_20170523_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvas',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='canvas',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
