
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-05-22T22:26:55-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "730d68fdd4a2da94b7b886f9c9f3eaddef1da8d2",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
