BBBB BBBB BBBBBBBBBBBBBBBB
XXXX XXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
    XXXX gettext(u'All activities') XXXXX
    BBB BB BB BBBBBBBBBBBBBBBBBBBBBB
      XXXX XXXXXXXX
           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX BBBBBBBBBBB BBX  BBBBBBBBBBBBBBBB BBXXXXXX
      BBB BB BB BBBBBBBBBBBB
        XXXX XXXXXXXX
             XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX BBBBBBBBBBB BBX  BBBBBBBBBBBBBBBB BBXXXXXX
        BBB B BB BBBBBBBBBBBB
          XXXX XXXXXXX
               XXXXXXXXXXXXXXXXXXXXXXXXXXXXX BBBBBBBBBBB BXX  BBBBBBBBBBBBBBBB B
            BB BBB BBBBBBBBBBBBB
              BBBBBBBBBBBBBBBBBBB B BB BBBBBBB
              XFFFFFFBB BBBBBBBBBBBBBBBXBBBBBX
            BBBBB
          XXXXXX
          BB BBBBBBBBBBBBB
            BBB B BB BBBBBBBBBBB
              BBBBBBBBBBBBBBBBBBB B BB BBBBBBB
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX BBBBBBBBBBB B BXX  BBBBBBBBBBBBBBBB B
                XFFFFFFBB BBBBBBBBBBBBBBBXBBBBBX
              XXXXXX
              BBB BB BB BBBBBBB
                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
              BBBBBB
            BBBBBB
          BBBB
            BBB BB BB BBBBBBB
              BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            BBBBBB
          BBBBB
        BBBBBB
      BBBBBB
    BBBBBB
  XXXXXX
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
XXXXXX
