BBBB BBBB
  XXXX gettext(u'Responsible contact persons')  XFFFFFFXXXXXX
  BBB B BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBB BBBBBBBBBBBBBBBB
  BBBBBB