 XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXX
    XXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      BBB BB BB BBBBBBBBBBBBBBBBBBBBBB
        XXXX
          XX XXXXXXXXXXXX XXXX
          XXX XXXXXXXXXX XXXXXXXXXXXXX
            BBB BB BB BBBBBBBBBBBB
              XXXX
                XX XXXXXXXXXXXX XXXX
                XXX XXXXXXXXXX XXXXXXXXXXXXX
                  BBB B BB BBBBBBBBBBBB
                    XXXX
                      XX XXXXXXXXXXX XXXX
                    XXXXX
                  BBBBBB
                XXXXX
              XXXXX
            BBBBBB
          XXXXX
        XXXXX
      BBBBBB
    XXXXX
  XXXXXX