BBBB BBBB BBBBBBBBBBBBBBBB
XXXX gettext(u'Participation to activities') XXXXX
BBB BB BB BBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBB BB BBBBBBBBBBB BB BBBBB
  BB BBBBB
    XXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX BBBBBBBBBBB BBX  BBBBBBBBBBBBBBBB BBXXXXXX
    BBB BB BB BBBBBBBBBBBB
      BBBBBBBBBBBBBBB BB BBBBBBBBBBB BB BBBBB
      BB BBBBB
        XXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX BBBBBBBBBBB BBX  BBBBBBBBBBBBBBBB BBXXXXXX
        BBB B BB BBBBBBBBBBBB
          BBBBBBBBBBBBBBB B BBBBBBBBBBB BB BBBB
          BB BBBB
            XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX BBBBBBBBBBB BXX  BBBBBBBBBBBBBBBB B
              BB BBB BBBBBBBBBBBBBXFFFFFFBB BBBBBBBBBBBBBBBXBBBBBXBBBBBXXXXXX
            BB BBBBBBBBBBBBB
              BBB B BB BBBBBBBBBBB
                BBBBBBBBBBBBBBB B BBBBBBBBBBB BB BBBB
                BB BBBB
                  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX BBBBBBBBBBB B BXX  BBBBBBBBBBBBBBBB B
                    XFFFFFFBB BBBBBBBBBBBBBBBXBBBBBX
                  XXXXXX
                  BBB BB BB BBBBBBBBBBBBBBBBBBBBB
                    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                  BBBBBB
                  BBB BB BB BBBBBBBBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXX
                      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    XXXXXX
                  BBBBBB
                BBBBB
              BBBBBB
            BBBB
              BBB BB BB BBBBBBBBBBBBBBBBBBBBB
                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
              BBBBBB
              XXXX XXXXXXXXXXXX
                BBB BB BB BBBBBBBBBBBBBBBBBBBBBBBBB
                  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                BBBBBB
              XXXXXX
            BBBBB
          BBBBB
        BBBBBB
      BBBBB
    BBBBBB
  BBBBB
BBBBBB

XXXX gettext(u'Answers to questions') XXXXX
BBB B BB BBBBBBBBBBBBBBBBBBBBBB
  BB BBBBBBBBBBBBB BB BBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
    XXXX
      BBB BB BB BBBBBBBBBBBBBBBBB
        BB BBBBBBBBB
          XXXXXX XXXXXXBBB BBBBBBBBBBB BBBBBBBBBBBBBBBBBXXXXXXX
          BB BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBB
            BB BBBBBBBBB
               gettext(u'Yes') 
            BBBB
               gettext(u'No') 
            BBBBB
          BBBB
            FFFFFFFFFFFF
          BBBBB
        BBBBB
      BBBBBB
    XXXXX
  BBBBB
BBBBBB