
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-05-02T23:09:58-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "a64723b510361e8f2be99be8623c8df92ae7d467",
 "version": "221.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
