BBBB BBBBBBBBBBBBBBBB BBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  BBBBBBBBBBBBB BB BBBBBBBBBBBBBBBB
  BB BBBBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
  XXXXXX
  BBBBB
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBBBB
      
    BBBB
      BB BBBBBBBBBBBBBB
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBXXXXXX
      BBBB
      XX XXXXXXBBB BBBBBBBBBBB BBBBBBBBBBBBBBXXXXXX
      BBBBB
    BBBBB
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX
        
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Number of activities') XX
      FFFFFFFFFFF
      XXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBB
        XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBB
          XXXXX XXXXXXXXX XXXXXXXXXXXXXXXX
        BBBBB
        BB BBBBBBBBBBBBBBBBBBB
          XXXXX XXXXXXXXX XXXXXXXXXXXXXX
        BBBBB
        BB BBBBBBBBBBBBBBB
          XXXXX XXXXXXXXX XXXXXXXXXXXXXXXX
        BBBBB
        XXXX
      BBBBB
    XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
BB BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBBBB
        XXX gettext(u'Additional info') XXXXXXXX
        FFFFFFFFFFFF
        XXXX
      BBBBB
      BB BBBBBBBBBBBBBBB
        XXX gettext(u'Log') XXXX
        XXXX
          BBB B BB BBBBBBBBBBBBBBB
            XXXX X XXXXX
          BBBBBB
        XXXXX
      BBBBB
    XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    FFFFFFFFFF
  XXXXXX
  XXXXXX
BBBBB