# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 19:33
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodyhealth',
            name='history',
            field=jsonfield.fields.JSONField(blank=True, default={}, null=True),
        ),
    ]
