BBBB BBBB
BB BBBBBBBBBBBBBBBBBBBB
  XXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
       gettext(u'Please fix errors below') 
    XXXXXX
  XXXXXX
BBBBB

BBB BBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBB
  BB BBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
  BBBB
    XXXXX
  BBBBB
  
XXXXXX
BBBBBB