
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-06-01T07:54:43+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "99f87a411dd9f642f0054ab5640bdcc0132f7f73",
 "version": "v0.1.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
