
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-05-02T19:56:57-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "8162de175aef861467c3091b7e1be2c5e72c509c",
 "version": "0.11.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
