
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-06-08T11:33:10-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "2f8eac76f31208fc8a9a9e23e40a19f205158251",
 "version": "2.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
