BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBBBBBBBBBBBB
BBBBB BBBBBBBBBBBB
  BBBBBBBBBB BBBBBBBBBBB BB BBBBBBB
  XXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXX
      XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
         XXXXXXXXXXXXXXXXXXXXXX
         XXXXXXXXXXXXX
         XXXXXXXXXXXXXXXXXXXX
         XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Admin') XXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXX
        BBB BBBB BB BBBBBBBBBBBBB
          BB BBBBBBBBBBBBBB
            XXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXX
                    XXXXXXXXXXXXXXXXX gettext(u'current') XXXXXXXXXXXXXXXXX
          BBBB
            XXXXXX XXXXXXXXXXXXXXXXX
          BBBBB
        BBBBBB
      XXXXX
    XXXXX
  XXXXX
BBBBBBBB