BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBBBBBBBBBBBBB
BBBBB BBBBBBBBBBBBB
  XXX gettext(u'If this is the first time you fill this form, you need a password to continue') XXXXX
  BB BBBBBBBBBBBBBBBBBBBBBBB
    XXXXXXX
  BBBBB
  BBBBBB BBBBBBBBBBBBB
BBBBBBBB