
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-05-23T11:06:14+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "3eea83e0b62b5682a17c7962e0efb612e8c128ea",
 "version": "0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
