
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.2.1'
version_full = '28656a48e5d8774c9c630a11e5f830fa118ef7cb'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

