# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rst/navigation/LabelCommand.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import rst.navigation.ExecutionParameters_pb2
import rst.navigation.MotionParameters_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rst/navigation/LabelCommand.proto',
  package='rst.navigation',
  serialized_pb='\n!rst/navigation/LabelCommand.proto\x12\x0erst.navigation\x1a(rst/navigation/ExecutionParameters.proto\x1a%rst/navigation/MotionParameters.proto\"\x9c\x01\n\x0cLabelCommand\x12\x0c\n\x04goal\x18\x01 \x02(\t\x12;\n\x11motion_parameters\x18\x02 \x01(\x0b\x32 .rst.navigation.MotionParameters\x12\x41\n\x14\x65xecution_parameters\x18\x03 \x01(\x0b\x32#.rst.navigation.ExecutionParametersB\x12\x42\x10LabelCommandType')




_LABELCOMMAND = _descriptor.Descriptor(
  name='LabelCommand',
  full_name='rst.navigation.LabelCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='goal', full_name='rst.navigation.LabelCommand.goal', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='motion_parameters', full_name='rst.navigation.LabelCommand.motion_parameters', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='execution_parameters', full_name='rst.navigation.LabelCommand.execution_parameters', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=135,
  serialized_end=291,
)

_LABELCOMMAND.fields_by_name['motion_parameters'].message_type = rst.navigation.MotionParameters_pb2._MOTIONPARAMETERS
_LABELCOMMAND.fields_by_name['execution_parameters'].message_type = rst.navigation.ExecutionParameters_pb2._EXECUTIONPARAMETERS
DESCRIPTOR.message_types_by_name['LabelCommand'] = _LABELCOMMAND

class LabelCommand(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LABELCOMMAND

  # @@protoc_insertion_point(class_scope:rst.navigation.LabelCommand)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'B\020LabelCommandType')
# @@protoc_insertion_point(module_scope)
