# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rst/navigation/OccupancyGrid2DInt.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import rst.geometry.Pose_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rst/navigation/OccupancyGrid2DInt.proto',
  package='rst.navigation',
  serialized_pb='\n\'rst/navigation/OccupancyGrid2DInt.proto\x12\x0erst.navigation\x1a\x17rst/geometry/Pose.proto\"x\n\x12OccupancyGrid2DInt\x12\x12\n\nresolution\x18\x01 \x02(\x02\x12\r\n\x05width\x18\x02 \x02(\r\x12\x0e\n\x06height\x18\x03 \x02(\r\x12\"\n\x06origin\x18\x04 \x02(\x0b\x32\x12.rst.geometry.Pose\x12\x0b\n\x03map\x18\x05 \x02(\x0c\x42\x18\x42\x16OccupancyGrid2DIntType')




_OCCUPANCYGRID2DINT = _descriptor.Descriptor(
  name='OccupancyGrid2DInt',
  full_name='rst.navigation.OccupancyGrid2DInt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='resolution', full_name='rst.navigation.OccupancyGrid2DInt.resolution', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='width', full_name='rst.navigation.OccupancyGrid2DInt.width', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height', full_name='rst.navigation.OccupancyGrid2DInt.height', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='origin', full_name='rst.navigation.OccupancyGrid2DInt.origin', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='map', full_name='rst.navigation.OccupancyGrid2DInt.map', index=4,
      number=5, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=84,
  serialized_end=204,
)

_OCCUPANCYGRID2DINT.fields_by_name['origin'].message_type = rst.geometry.Pose_pb2._POSE
DESCRIPTOR.message_types_by_name['OccupancyGrid2DInt'] = _OCCUPANCYGRID2DINT

class OccupancyGrid2DInt(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _OCCUPANCYGRID2DINT

  # @@protoc_insertion_point(class_scope:rst.navigation.OccupancyGrid2DInt)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'B\026OccupancyGrid2DIntType')
# @@protoc_insertion_point(module_scope)
