from ....tl.mtproto_request import MTProtoRequest


class RequestPasswordRecoveryRequest(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    auth.requestPasswordRecovery#d897bc66  = auth.PasswordRecovery"""

    # Telegram's constructor ID (and unique identifier) for this class
    constructor_id = 0xd897bc66

    def __init__(self):
        super().__init__()
        self.result = None
        self.confirmed = True  # Confirmed by default

    def on_send(self, writer):
        writer.write_int(RequestPasswordRecoveryRequest.constructor_id, signed=False)

    @staticmethod
    def empty():
        """Returns an "empty" instance (all attributes are None)"""
        return RequestPasswordRecoveryRequest()

    def on_response(self, reader):
        self.result = reader.tgread_object()

    def __repr__(self):
        return 'auth.requestPasswordRecovery#d897bc66  = auth.PasswordRecovery'

    def __str__(self):
        return '(auth.requestPasswordRecovery (ID: 0xd897bc66) = ())'.format()
