from django.conf import settings

SLIDER_SIZE_PC = (1000, 500)
SLIDER_SIZE_TABLET = (1000, 500)
SLIDER_SIZE_MOBILE = (1000, 500)

SLIDER_FORMAT = 'PNG'

SLIDER_OPTIONS = {
    'quality': 70
}

PAGE_SLIDER_PC_SIZES = getattr(settings, 'SLIDER_SIZE_PC', SLIDER_SIZE_PC)
PAGE_SLIDER_TABLET_SIZES = getattr(settings, 'SLIDER_SIZE_TABLET', SLIDER_SIZE_TABLET)
PAGE_SLIDER_MOBILE_SIZES = getattr(settings, 'SLIDER_SIZE_MOBILE', SLIDER_SIZE_MOBILE)

PAGE_SLIDER_FORMAT = getattr(settings, 'SLIDER_FORMAT', SLIDER_FORMAT)

PAGE_SLIDER_OPTIONS = getattr(settings, 'SLIDER_OPTIONS', SLIDER_OPTIONS)

SLIDER_TYPE_CONTENT = [
    'TEXT',
    'BUTTON',
]