# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rst/math/Vec2DFloat.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rst/math/Vec2DFloat.proto',
  package='rst.math',
  serialized_pb='\n\x19rst/math/Vec2DFloat.proto\x12\x08rst.math\"(\n\nVec2DFloat\x12\x0c\n\x01x\x18\x01 \x02(\x02:\x01\x30\x12\x0c\n\x01y\x18\x02 \x02(\x02:\x01\x30\x42\x10\x42\x0eVec2DFloatType')




_VEC2DFLOAT = _descriptor.Descriptor(
  name='Vec2DFloat',
  full_name='rst.math.Vec2DFloat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='rst.math.Vec2DFloat.x', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='rst.math.Vec2DFloat.y', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=39,
  serialized_end=79,
)

DESCRIPTOR.message_types_by_name['Vec2DFloat'] = _VEC2DFLOAT

class Vec2DFloat(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VEC2DFLOAT

  # @@protoc_insertion_point(class_scope:rst.math.Vec2DFloat)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'B\016Vec2DFloatType')
# @@protoc_insertion_point(module_scope)
