BBBB BBBBBBBBBBBBBBBB
BBBB BBBB
BB BBBBBBBBBBB
  XXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
       gettext(u'Please fix errors below') 
    XXXXXX
  XXXXXX
BBBBB

BB BBBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBB
BBBB
BBB BBBBBBBBB BB BBBBBBBBBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBB
BBBBB
