# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createUser.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CreateUser(object):
    def setupUi(self, CreateUser):
        CreateUser.setObjectName("CreateUser")
        CreateUser.resize(640, 480)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(CreateUser)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(CreateUser)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.new_password_check = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_password_check.sizePolicy().hasHeightForWidth())
        self.new_password_check.setSizePolicy(sizePolicy)
        self.new_password_check.setText("")
        self.new_password_check.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.new_password_check.setObjectName("new_password_check")
        self.gridLayout_2.addWidget(self.new_password_check, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.new_name = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_name.sizePolicy().hasHeightForWidth())
        self.new_name.setSizePolicy(sizePolicy)
        self.new_name.setText("")
        self.new_name.setObjectName("new_name")
        self.gridLayout_2.addWidget(self.new_name, 0, 1, 1, 1)
        self.new_password = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_password.sizePolicy().hasHeightForWidth())
        self.new_password.setSizePolicy(sizePolicy)
        self.new_password.setText("")
        self.new_password.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.new_password.setObjectName("new_password")
        self.gridLayout_2.addWidget(self.new_password, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(CreateUser)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.root_name = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.root_name.sizePolicy().hasHeightForWidth())
        self.root_name.setSizePolicy(sizePolicy)
        self.root_name.setText("")
        self.root_name.setObjectName("root_name")
        self.gridLayout.addWidget(self.root_name, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.root_password = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.root_password.sizePolicy().hasHeightForWidth())
        self.root_password.setSizePolicy(sizePolicy)
        self.root_password.setText("")
        self.root_password.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.root_password.setObjectName("root_password")
        self.gridLayout.addWidget(self.root_password, 1, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(CreateUser)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.check_show_passwords = QtWidgets.QCheckBox(self.groupBox)
        self.check_show_passwords.setObjectName("check_show_passwords")
        self.verticalLayout.addWidget(self.check_show_passwords)
        self.verticalLayout_3.addWidget(self.groupBox)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(CreateUser)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)
        self.verticalLayout_3.setStretch(4, 1)

        self.retranslateUi(CreateUser)
        self.buttonBox.accepted.connect(CreateUser.accept)
        self.buttonBox.rejected.connect(CreateUser.reject)
        QtCore.QMetaObject.connectSlotsByName(CreateUser)
        CreateUser.setTabOrder(self.root_name, self.root_password)
        CreateUser.setTabOrder(self.root_password, self.new_name)
        CreateUser.setTabOrder(self.new_name, self.new_password)
        CreateUser.setTabOrder(self.new_password, self.new_password_check)
        CreateUser.setTabOrder(self.new_password_check, self.check_show_passwords)
        CreateUser.setTabOrder(self.check_show_passwords, self.buttonBox)

    def retranslateUi(self, CreateUser):
        _translate = QtCore.QCoreApplication.translate
        CreateUser.setWindowTitle(_translate("CreateUser", "Create a new MySQL user – Coquery"))
        self.groupBox_2.setTitle(_translate("CreateUser", "New user"))
        self.label_4.setText(_translate("CreateUser", "Password:"))
        self.label_6.setText(_translate("CreateUser", "Retype password::"))
        self.label_5.setText(_translate("CreateUser", "New user name:"))
        self.label_7.setText(_translate("CreateUser", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">New users will be able to create, query, modify, and delete databases and tables</li>\n"
"<li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">New users will <span style=\" font-weight:600;\">not be able</span> to create or modify the privileges of other users</li></ul></body></html>"))
        self.groupBox_3.setTitle(_translate("CreateUser", "MySQL root"))
        self.label_3.setText(_translate("CreateUser", "MySQL root user:"))
        self.label_2.setText(_translate("CreateUser", "MySQL root password:"))
        self.check_show_passwords.setText(_translate("CreateUser", "Show passwords"))


