# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'figureOptions_full.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FigureOptions(object):
    def setupUi(self, FigureOptions):
        FigureOptions.setObjectName("FigureOptions")
        FigureOptions.resize(476, 678)
        self.gridLayout = QtWidgets.QGridLayout(FigureOptions)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(FigureOptions)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(FigureOptions)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_labels = QtWidgets.QWidget()
        self.tab_labels.setObjectName("tab_labels")
        self.formLayout = QtWidgets.QFormLayout(self.tab_labels)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_5 = QtWidgets.QLabel(self.tab_labels)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_main = QtWidgets.QLineEdit(self.tab_labels)
        self.label_main.setObjectName("label_main")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_main)
        self.label_6 = QtWidgets.QLabel(self.tab_labels)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_x_axis = QtWidgets.QLineEdit(self.tab_labels)
        self.label_x_axis.setObjectName("label_x_axis")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_x_axis)
        self.label_7 = QtWidgets.QLabel(self.tab_labels)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_y_axis = QtWidgets.QLineEdit(self.tab_labels)
        self.label_y_axis.setObjectName("label_y_axis")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_y_axis)
        self.label_8 = QtWidgets.QLabel(self.tab_labels)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_legend = QtWidgets.QLineEdit(self.tab_labels)
        self.label_legend.setObjectName("label_legend")
        self.verticalLayout_4.addWidget(self.label_legend)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_13 = QtWidgets.QLabel(self.tab_labels)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_7.addWidget(self.label_13)
        self.spin_columns = QtWidgets.QSpinBox(self.tab_labels)
        self.spin_columns.setMinimum(1)
        self.spin_columns.setMaximum(9)
        self.spin_columns.setProperty("value", 1)
        self.spin_columns.setObjectName("spin_columns")
        self.horizontalLayout_7.addWidget(self.spin_columns)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_4)
        self.tabWidget.addTab(self.tab_labels, "")
        self.tab_colors = QtWidgets.QWidget()
        self.tab_colors.setObjectName("tab_colors")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_colors)
        self.verticalLayout_3.setContentsMargins(8, 6, 8, 6)
        self.verticalLayout_3.setSpacing(16)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.tab_colors)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setWordWrap(True)
        self.label_15.setOpenExternalLinks(True)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_7.addWidget(self.label_15)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.radio_qualitative = QtWidgets.QRadioButton(self.frame_2)
        self.radio_qualitative.setChecked(True)
        self.radio_qualitative.setObjectName("radio_qualitative")
        self.gridLayout_6.addWidget(self.radio_qualitative, 0, 0, 1, 1)
        self.combo_qualitative = QtWidgets.QComboBox(self.frame_2)
        self.combo_qualitative.setObjectName("combo_qualitative")
        self.combo_qualitative.addItem("")
        self.combo_qualitative.addItem("")
        self.combo_qualitative.addItem("")
        self.combo_qualitative.addItem("")
        self.combo_qualitative.addItem("")
        self.combo_qualitative.addItem("")
        self.combo_qualitative.addItem("")
        self.combo_qualitative.addItem("")
        self.gridLayout_6.addWidget(self.combo_qualitative, 0, 1, 1, 1)
        self.radio_sequential = QtWidgets.QRadioButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_sequential.sizePolicy().hasHeightForWidth())
        self.radio_sequential.setSizePolicy(sizePolicy)
        self.radio_sequential.setObjectName("radio_sequential")
        self.gridLayout_6.addWidget(self.radio_sequential, 1, 0, 1, 1)
        self.combo_sequential = QtWidgets.QComboBox(self.frame_2)
        self.combo_sequential.setObjectName("combo_sequential")
        self.combo_sequential.addItem("")
        self.combo_sequential.addItem("")
        self.combo_sequential.addItem("")
        self.combo_sequential.addItem("")
        self.combo_sequential.addItem("")
        self.combo_sequential.addItem("")
        self.combo_sequential.addItem("")
        self.combo_sequential.addItem("")
        self.combo_sequential.addItem("")
        self.combo_sequential.addItem("")
        self.combo_sequential.addItem("")
        self.combo_sequential.addItem("")
        self.combo_sequential.addItem("")
        self.combo_sequential.addItem("")
        self.combo_sequential.addItem("")
        self.combo_sequential.addItem("")
        self.combo_sequential.addItem("")
        self.combo_sequential.addItem("")
        self.gridLayout_6.addWidget(self.combo_sequential, 1, 1, 1, 1)
        self.radio_diverging = QtWidgets.QRadioButton(self.frame_2)
        self.radio_diverging.setObjectName("radio_diverging")
        self.gridLayout_6.addWidget(self.radio_diverging, 2, 0, 1, 1)
        self.combo_diverging = QtWidgets.QComboBox(self.frame_2)
        self.combo_diverging.setObjectName("combo_diverging")
        self.combo_diverging.addItem("")
        self.combo_diverging.addItem("")
        self.combo_diverging.addItem("")
        self.combo_diverging.addItem("")
        self.combo_diverging.addItem("")
        self.combo_diverging.addItem("")
        self.combo_diverging.addItem("")
        self.combo_diverging.addItem("")
        self.gridLayout_6.addWidget(self.combo_diverging, 2, 1, 1, 1)
        self.radio_custom = QtWidgets.QRadioButton(self.frame_2)
        self.radio_custom.setObjectName("radio_custom")
        self.gridLayout_6.addWidget(self.radio_custom, 3, 0, 1, 1)
        self.combo_custom = QtWidgets.QComboBox(self.frame_2)
        self.combo_custom.setObjectName("combo_custom")
        self.gridLayout_6.addWidget(self.combo_custom, 3, 1, 1, 1)
        self.button_remove_custom = QtWidgets.QPushButton(self.frame_2)
        self.button_remove_custom.setObjectName("button_remove_custom")
        self.gridLayout_6.addWidget(self.button_remove_custom, 3, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem1, 3, 3, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_6)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.tab_colors)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.spin_number = QtWidgets.QSpinBox(self.frame)
        self.spin_number.setMinimum(1)
        self.spin_number.setProperty("value", 6)
        self.spin_number.setObjectName("spin_number")
        self.horizontalLayout_6.addWidget(self.spin_number)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.verticalLayout_3.addWidget(self.frame)
        self.frame1 = QtWidgets.QFrame(self.tab_colors)
        self.frame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame1.setObjectName("frame1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_14 = QtWidgets.QLabel(self.frame1)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_5.addWidget(self.label_14)
        self.color_test_area = QtWidgets.QListWidget(self.frame1)
        self.color_test_area.setDragEnabled(True)
        self.color_test_area.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.color_test_area.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.color_test_area.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.color_test_area.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.color_test_area.setMovement(QtWidgets.QListView.Snap)
        self.color_test_area.setObjectName("color_test_area")
        self.verticalLayout_5.addWidget(self.color_test_area)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.button_reverse_order = QtWidgets.QPushButton(self.frame1)
        self.button_reverse_order.setObjectName("button_reverse_order")
        self.horizontalLayout_8.addWidget(self.button_reverse_order)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.verticalLayout_3.addWidget(self.frame1)
        self.frame.raise_()
        self.frame.raise_()
        self.frame_2.raise_()
        self.tabWidget.addTab(self.tab_colors, "")
        self.tab_fonts = QtWidgets.QWidget()
        self.tab_fonts.setObjectName("tab_fonts")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_fonts)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_fonts)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 452, 505))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.group_main = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.group_main.setObjectName("group_main")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.group_main)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.group_main)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_sample_main = QtWidgets.QLabel(self.group_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sample_main.sizePolicy().hasHeightForWidth())
        self.label_sample_main.setSizePolicy(sizePolicy)
        self.label_sample_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_sample_main.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_sample_main.setObjectName("label_sample_main")
        self.horizontalLayout.addWidget(self.label_sample_main)
        self.button_select_main = QtWidgets.QPushButton(self.group_main)
        self.button_select_main.setObjectName("button_select_main")
        self.horizontalLayout.addWidget(self.button_select_main)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.group_main)
        self.group_x_axis = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.group_x_axis.setObjectName("group_x_axis")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.group_x_axis)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.group_x_axis)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_sample_x_axis = QtWidgets.QLabel(self.group_x_axis)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sample_x_axis.sizePolicy().hasHeightForWidth())
        self.label_sample_x_axis.setSizePolicy(sizePolicy)
        self.label_sample_x_axis.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_sample_x_axis.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_sample_x_axis.setObjectName("label_sample_x_axis")
        self.horizontalLayout_2.addWidget(self.label_sample_x_axis)
        self.button_select_x_axis = QtWidgets.QPushButton(self.group_x_axis)
        self.button_select_x_axis.setObjectName("button_select_x_axis")
        self.horizontalLayout_2.addWidget(self.button_select_x_axis)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.group_x_axis)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_sample_x_ticks = QtWidgets.QLabel(self.group_x_axis)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sample_x_ticks.sizePolicy().hasHeightForWidth())
        self.label_sample_x_ticks.setSizePolicy(sizePolicy)
        self.label_sample_x_ticks.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_sample_x_ticks.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_sample_x_ticks.setObjectName("label_sample_x_ticks")
        self.horizontalLayout_4.addWidget(self.label_sample_x_ticks)
        self.button_select_x_ticks = QtWidgets.QPushButton(self.group_x_axis)
        self.button_select_x_ticks.setObjectName("button_select_x_ticks")
        self.horizontalLayout_4.addWidget(self.button_select_x_ticks)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.group_x_axis)
        self.group_y_axis = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.group_y_axis.setObjectName("group_y_axis")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.group_y_axis)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_9 = QtWidgets.QLabel(self.group_y_axis)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_sample_y_axis = QtWidgets.QLabel(self.group_y_axis)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sample_y_axis.sizePolicy().hasHeightForWidth())
        self.label_sample_y_axis.setSizePolicy(sizePolicy)
        self.label_sample_y_axis.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_sample_y_axis.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_sample_y_axis.setObjectName("label_sample_y_axis")
        self.horizontalLayout_3.addWidget(self.label_sample_y_axis)
        self.button_select_y_axis = QtWidgets.QPushButton(self.group_y_axis)
        self.button_select_y_axis.setObjectName("button_select_y_axis")
        self.horizontalLayout_3.addWidget(self.button_select_y_axis)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.group_y_axis)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_sample_y_ticks = QtWidgets.QLabel(self.group_y_axis)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sample_y_ticks.sizePolicy().hasHeightForWidth())
        self.label_sample_y_ticks.setSizePolicy(sizePolicy)
        self.label_sample_y_ticks.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_sample_y_ticks.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_sample_y_ticks.setObjectName("label_sample_y_ticks")
        self.horizontalLayout_5.addWidget(self.label_sample_y_ticks)
        self.button_select_y_ticks = QtWidgets.QPushButton(self.group_y_axis)
        self.button_select_y_ticks.setObjectName("button_select_y_ticks")
        self.horizontalLayout_5.addWidget(self.button_select_y_ticks)
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.group_y_axis)
        self.group_legend = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.group_legend.setObjectName("group_legend")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.group_legend)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_11 = QtWidgets.QLabel(self.group_legend)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 0, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_sample_legend = QtWidgets.QLabel(self.group_legend)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sample_legend.sizePolicy().hasHeightForWidth())
        self.label_sample_legend.setSizePolicy(sizePolicy)
        self.label_sample_legend.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_sample_legend.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_sample_legend.setObjectName("label_sample_legend")
        self.horizontalLayout_12.addWidget(self.label_sample_legend)
        self.button_select_legend = QtWidgets.QPushButton(self.group_legend)
        self.button_select_legend.setObjectName("button_select_legend")
        self.horizontalLayout_12.addWidget(self.button_select_legend)
        self.gridLayout_5.addLayout(self.horizontalLayout_12, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.group_legend)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 1, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_sample_legend_entries = QtWidgets.QLabel(self.group_legend)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sample_legend_entries.sizePolicy().hasHeightForWidth())
        self.label_sample_legend_entries.setSizePolicy(sizePolicy)
        self.label_sample_legend_entries.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_sample_legend_entries.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_sample_legend_entries.setObjectName("label_sample_legend_entries")
        self.horizontalLayout_13.addWidget(self.label_sample_legend_entries)
        self.button_select_legend_entries = QtWidgets.QPushButton(self.group_legend)
        self.button_select_legend_entries.setObjectName("button_select_legend_entries")
        self.horizontalLayout_13.addWidget(self.button_select_legend_entries)
        self.gridLayout_5.addLayout(self.horizontalLayout_13, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.group_legend)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.pushButton = QtWidgets.QPushButton(self.tab_fonts)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_11.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        spacerItem5 = QtWidgets.QSpacerItem(20, 220, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.verticalLayout.setStretch(2, 1)
        self.tabWidget.addTab(self.tab_fonts, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(FigureOptions)
        self.tabWidget.setCurrentIndex(2)
        self.buttonBox.accepted.connect(FigureOptions.accept)
        self.buttonBox.rejected.connect(FigureOptions.reject)
        QtCore.QMetaObject.connectSlotsByName(FigureOptions)

    def retranslateUi(self, FigureOptions):
        _translate = QtCore.QCoreApplication.translate
        FigureOptions.setWindowTitle(_translate("FigureOptions", "Figure options – Coquery"))
        self.label_5.setText(_translate("FigureOptions", "Main"))
        self.label_6.setText(_translate("FigureOptions", "X axis"))
        self.label_7.setText(_translate("FigureOptions", "Y axis"))
        self.label_8.setText(_translate("FigureOptions", "Legend"))
        self.label_13.setText(_translate("FigureOptions", "Number of columns in legend:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_labels), _translate("FigureOptions", "Labels"))
        self.label_15.setText(_translate("FigureOptions", "<html><head/><body><p>Choose palette:<br/>(see <a href=\"http://colorbrewer2.org\"><span style=\" text-decoration: underline; color:#006e28;\">http://colorbrewer2.org</span></a> for a demonstration)</p></body></html>"))
        self.radio_qualitative.setText(_translate("FigureOptions", "Qualitative"))
        self.combo_qualitative.setItemText(0, _translate("FigureOptions", "Set1"))
        self.combo_qualitative.setItemText(1, _translate("FigureOptions", "Set2"))
        self.combo_qualitative.setItemText(2, _translate("FigureOptions", "Set3"))
        self.combo_qualitative.setItemText(3, _translate("FigureOptions", "Paired"))
        self.combo_qualitative.setItemText(4, _translate("FigureOptions", "Accent"))
        self.combo_qualitative.setItemText(5, _translate("FigureOptions", "Pastel1"))
        self.combo_qualitative.setItemText(6, _translate("FigureOptions", "Pastel2"))
        self.combo_qualitative.setItemText(7, _translate("FigureOptions", "Dark2"))
        self.radio_sequential.setText(_translate("FigureOptions", "Sequential"))
        self.combo_sequential.setItemText(0, _translate("FigureOptions", "Greys"))
        self.combo_sequential.setItemText(1, _translate("FigureOptions", "Reds"))
        self.combo_sequential.setItemText(2, _translate("FigureOptions", "Greens"))
        self.combo_sequential.setItemText(3, _translate("FigureOptions", "Blues"))
        self.combo_sequential.setItemText(4, _translate("FigureOptions", "Oranges"))
        self.combo_sequential.setItemText(5, _translate("FigureOptions", "Purples"))
        self.combo_sequential.setItemText(6, _translate("FigureOptions", "BuGn"))
        self.combo_sequential.setItemText(7, _translate("FigureOptions", "BuPu"))
        self.combo_sequential.setItemText(8, _translate("FigureOptions", "GnBu"))
        self.combo_sequential.setItemText(9, _translate("FigureOptions", "OrRd"))
        self.combo_sequential.setItemText(10, _translate("FigureOptions", "PuBu"))
        self.combo_sequential.setItemText(11, _translate("FigureOptions", "PuRd"))
        self.combo_sequential.setItemText(12, _translate("FigureOptions", "RdPu"))
        self.combo_sequential.setItemText(13, _translate("FigureOptions", "YlGn"))
        self.combo_sequential.setItemText(14, _translate("FigureOptions", "PuBuGn"))
        self.combo_sequential.setItemText(15, _translate("FigureOptions", "YlGnBu"))
        self.combo_sequential.setItemText(16, _translate("FigureOptions", "YlOrBr"))
        self.combo_sequential.setItemText(17, _translate("FigureOptions", "YlOrRd"))
        self.radio_diverging.setText(_translate("FigureOptions", "Diverging"))
        self.combo_diverging.setItemText(0, _translate("FigureOptions", "RdBu"))
        self.combo_diverging.setItemText(1, _translate("FigureOptions", "RdGy"))
        self.combo_diverging.setItemText(2, _translate("FigureOptions", "PRGn"))
        self.combo_diverging.setItemText(3, _translate("FigureOptions", "PiYG"))
        self.combo_diverging.setItemText(4, _translate("FigureOptions", "BrBG"))
        self.combo_diverging.setItemText(5, _translate("FigureOptions", "RdYlBu"))
        self.combo_diverging.setItemText(6, _translate("FigureOptions", "RdYlGn"))
        self.combo_diverging.setItemText(7, _translate("FigureOptions", "Spectral"))
        self.radio_custom.setText(_translate("FigureOptions", "Custom"))
        self.button_remove_custom.setText(_translate("FigureOptions", "Remove"))
        self.label_4.setText(_translate("FigureOptions", "Number of colors:"))
        self.label_14.setText(_translate("FigureOptions", "Click to modify color, drag to change order:"))
        self.button_reverse_order.setText(_translate("FigureOptions", "Reverse order"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_colors), _translate("FigureOptions", "Colors"))
        self.group_main.setTitle(_translate("FigureOptions", "Main"))
        self.label.setText(_translate("FigureOptions", "Label"))
        self.label_sample_main.setText(_translate("FigureOptions", "Default font"))
        self.button_select_main.setText(_translate("FigureOptions", "Select..."))
        self.group_x_axis.setTitle(_translate("FigureOptions", "X axis"))
        self.label_2.setText(_translate("FigureOptions", "Label"))
        self.label_sample_x_axis.setText(_translate("FigureOptions", "Default font"))
        self.button_select_x_axis.setText(_translate("FigureOptions", "Select..."))
        self.label_3.setText(_translate("FigureOptions", "Ticks"))
        self.label_sample_x_ticks.setText(_translate("FigureOptions", "Default font"))
        self.button_select_x_ticks.setText(_translate("FigureOptions", "Select..."))
        self.group_y_axis.setTitle(_translate("FigureOptions", "Y axis"))
        self.label_9.setText(_translate("FigureOptions", "Label"))
        self.label_sample_y_axis.setText(_translate("FigureOptions", "Default font"))
        self.button_select_y_axis.setText(_translate("FigureOptions", "Select..."))
        self.label_10.setText(_translate("FigureOptions", "Ticks"))
        self.label_sample_y_ticks.setText(_translate("FigureOptions", "Default font"))
        self.button_select_y_ticks.setText(_translate("FigureOptions", "Select..."))
        self.group_legend.setTitle(_translate("FigureOptions", "Legend"))
        self.label_11.setText(_translate("FigureOptions", "Label"))
        self.label_sample_legend.setText(_translate("FigureOptions", "Default font"))
        self.button_select_legend.setText(_translate("FigureOptions", "Select..."))
        self.label_12.setText(_translate("FigureOptions", "Entries"))
        self.label_sample_legend_entries.setText(_translate("FigureOptions", "Default font"))
        self.button_select_legend_entries.setText(_translate("FigureOptions", "Select..."))
        self.pushButton.setText(_translate("FigureOptions", "Select font for all..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_fonts), _translate("FigureOptions", "Fonts"))


