# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-12 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slothTw', '0012_auto_20170612_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likesfromuser',
            name='course',
        ),
        migrations.AlterField(
            model_name='pagelog',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slothTw.Course'),
        ),
        migrations.AlterField(
            model_name='pagelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infernoWeb.User'),
        ),
    ]
