# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-03 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slothTw', '0007_remove_course_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='emotion',
            field=models.CharField(choices=[('neutral', 'neutral'), ('pos', 'pos'), ('neg', 'neg')], default='neutral', max_length=7),
        ),
    ]
