BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBB BBBBBB BBBBBBBBBBBBBBBB
BBBBB BBB
  BBBBBBBB BBB
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
  BBBBBBBBBBB
  
BBBBBBBB

BBBB BBBB BBBBBBBBBBBBBBBB
BBBBB BBBBBBB
  XXXX gettext(u'Responsible person contact details') XXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    FFFFFFFFFF
     gettext(u'Can see full report') X FFFFFFFFFFFFFF
  XXXXXX

  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

  XXXX gettext(u'Configuration') XXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXX gettext(u'Show participations from earlier revisions') XXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Expand all info') XXXXXXXX
    XXXXXX
  XXXXXX

  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBB

