BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBBBBBBBBBBBBB BBBB
BBBBB BBBBBBB
  
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX gettext(u'Contact details') SSSSSSS SSSSSSSXXXXXX

    BBB BBBBBBB BBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          FFFFFFFFFF
        XXXXXX
      XXXXXX
    BBBBBB

  XXXXXX
  
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX gettext(u'I am wishing to participate in the following activities') S SS SSSSSSS SS SSSSSSSSSSS SS SSS SSSSSSSSS SSSSSSSSSSXXXXXX
    XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXX
         gettext(u'Activity') 
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXX
         gettext(u'Additional info') 
      XXXXXX
    XXXXXX

    BBB B BB BBBBBBBBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          FFFFFFFFFF
        XXXXXX
      XXXXXX
      BBB B BB BBBBBBBBB
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            FFFFFFFFFF
          XXXXXX
        XXXXXX
      BBBBBB
    BBBBBB

  XXXXXX
  
  BB BBBBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX gettext(u'Answers to questions') SSSSSSS SS SSSSSSSSSXXXXXX
      XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
           gettext(u'Question') 
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
           gettext(u'Answer') 
        XXXXXX
      XXXXXX
      BBB B BB BBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBB
              BB BBBBBBBB
                 gettext(u'Yes') 
              BBBB
                 gettext(u'No') 
              BBBBB
            BBBB
              FFFFFFFFFF
            BBBBB
          XXXXXX
        XXXXXX
      BBBBBB
    XXXXXX
  BBBBB

  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX gettext(u'Other information') SSSSS SSSSSSSSSSSXXXXXX

    BBB BBBBBBB BBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          FFFFFFFFFFFFFFFFFF
        XXXXXX
      XXXXXX
    BBBBBB

  XXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXX gettext(u'Log') XXXXX
    XXXX
      BBB B BB BBBBBBBBBBBBBBB
        XXXX X XXXXX
      BBBBBB
    XXXXX
    XXXXX XXXXXXXXXXXXXX
      BBBBBBBBBB
      XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX
                                                                                        XXXXXXX gettext(u'Add entry') X
                                                                                        XXXXXXXXXX XXXXXXXXXXXX
                                                                                        XXXXXXXXXXXX
    XXXXXXX
    XXXXXX
BBBBBBBB