# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-06 07:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slothTw', '0010_likesfromuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likesfromuser',
            old_name='Comment',
            new_name='comment',
        ),
    ]
