# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-19 05:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slothTw', '0002_auto_20170419_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='create',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
