# Autogenerated by Astropy-affiliated package astropy_helpers's setup.py on 2017-03-15 13:54:33.713393
from __future__ import unicode_literals
import datetime

version = "1.3"
githash = "f06ca37c4e389b90556815b300d9992fa3945199"


major = 1
minor = 3
bugfix = 0

release = True
timestamp = datetime.datetime(2017, 3, 15, 13, 54, 33, 713393)
debug = False

try:
    from ._compiler import compiler
except ImportError:
    compiler = "unknown"

try:
    from .cython_version import cython_version
except ImportError:
    cython_version = "unknown"
