# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rst/tracking/TrackedPosition3DFloat.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import rst.tracking.TrackingInfo_pb2
import rst.geometry.Translation_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rst/tracking/TrackedPosition3DFloat.proto',
  package='rst.tracking',
  serialized_pb='\n)rst/tracking/TrackedPosition3DFloat.proto\x12\x0crst.tracking\x1a\x1frst/tracking/TrackingInfo.proto\x1a\x1erst/geometry/Translation.proto\"\x83\x01\n\x16TrackedPosition3DFloat\x12(\n\x04info\x18\x01 \x02(\x0b\x32\x1a.rst.tracking.TrackingInfo\x12+\n\x08position\x18\x02 \x02(\x0b\x32\x19.rst.geometry.Translation\x12\x12\n\nconfidence\x18\x03 \x02(\x02\x42\x1c\x42\x1aTrackedPosition3DFloatType')




_TRACKEDPOSITION3DFLOAT = _descriptor.Descriptor(
  name='TrackedPosition3DFloat',
  full_name='rst.tracking.TrackedPosition3DFloat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='rst.tracking.TrackedPosition3DFloat.info', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position', full_name='rst.tracking.TrackedPosition3DFloat.position', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='rst.tracking.TrackedPosition3DFloat.confidence', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=125,
  serialized_end=256,
)

_TRACKEDPOSITION3DFLOAT.fields_by_name['info'].message_type = rst.tracking.TrackingInfo_pb2._TRACKINGINFO
_TRACKEDPOSITION3DFLOAT.fields_by_name['position'].message_type = rst.geometry.Translation_pb2._TRANSLATION
DESCRIPTOR.message_types_by_name['TrackedPosition3DFloat'] = _TRACKEDPOSITION3DFLOAT

class TrackedPosition3DFloat(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TRACKEDPOSITION3DFLOAT

  # @@protoc_insertion_point(class_scope:rst.tracking.TrackedPosition3DFloat)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'B\032TrackedPosition3DFloatType')
# @@protoc_insertion_point(module_scope)
