# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rst/tracking/TrackedPositions3DFloat.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import rst.tracking.TrackedPosition3DFloat_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rst/tracking/TrackedPositions3DFloat.proto',
  package='rst.tracking',
  serialized_pb='\n*rst/tracking/TrackedPositions3DFloat.proto\x12\x0crst.tracking\x1a)rst/tracking/TrackedPosition3DFloat.proto\"Q\n\x17TrackedPositions3DFloat\x12\x36\n\x08position\x18\x01 \x03(\x0b\x32$.rst.tracking.TrackedPosition3DFloatB\x1d\x42\x1bTrackedPositions3DFloatType')




_TRACKEDPOSITIONS3DFLOAT = _descriptor.Descriptor(
  name='TrackedPositions3DFloat',
  full_name='rst.tracking.TrackedPositions3DFloat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='rst.tracking.TrackedPositions3DFloat.position', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=103,
  serialized_end=184,
)

_TRACKEDPOSITIONS3DFLOAT.fields_by_name['position'].message_type = rst.tracking.TrackedPosition3DFloat_pb2._TRACKEDPOSITION3DFLOAT
DESCRIPTOR.message_types_by_name['TrackedPositions3DFloat'] = _TRACKEDPOSITIONS3DFLOAT

class TrackedPositions3DFloat(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TRACKEDPOSITIONS3DFLOAT

  # @@protoc_insertion_point(class_scope:rst.tracking.TrackedPositions3DFloat)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'B\033TrackedPositions3DFloatType')
# @@protoc_insertion_point(module_scope)
