BBBB BBBB BBBBBBBBBBBBBBBB
BB BBBBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
      
    XXXXXX
  XXXXXX
BBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBBX BBBBBBBBBBB BBB BX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          BB BBBBBBBBBBBBBBBBBBBBBB
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                   BB BBBBBBBBBBBBBBBBBXXXXXXXBBBBBX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
          BBBBB
          
        XXXXXX
      XXXXXX
    XXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBB
          XXXXX XXXXXXXXX XXXXXXXXXXXXXXXX
        BBBBB
        BB BBB BBBBBBBBBBBBBBBBBBBB
          XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
        BBBBB
      XXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      
        BB BBBBBBBBBBBBBBBBBBBB
          XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXX XXXXXXXXXXXXXX
        XXXX
        BBBBB
      BBBBB
    XXXXXX
  XXXXXX
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BB BBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      BBB BBBBBB BB BBBBBBBBBBBBBBBBBB
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBB
      BBBBBB
    XXXXXX
  BBBBB
XXXXXX