BBBB BBBB BBBBBBBBBBBBBBBB
BB BBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX BBBBBBBBBBB BBBX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX

    XXXXXX

      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBBBBB
        
      XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBBBBB
          XXXXX XXXXXXXXX XXXXXXXXXXXXXX
        BBBBB
      XXXX
        BBBBB
      XXXXXX
  XXXXXX


  XXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX BBBBBBBBBBB BBB BX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    BBB BBBB BB BBBBBBBBBBBBBBBBBBBB
      BB BBBBBBBBBBBBBXXX gettext(u'Responsible contact person(s)') X XXXXBBBBB
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBB
    BBBBBB
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX
XXXXXX


  BB BBBBBBBBBBBBBBB
  XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX BBBBBBBBBBB BBBX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    XXXXXX
  XXXXXX
  BBBBB
BBBBB