BBBB BBBB BBBBBBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBBX BBBBBBBBBBB BBB BX
  XXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX
              BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                       XXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBXXXXXXXBBBBBX
              BBBB
                XXXXXXXXXXXX XXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                       XXXXXXXXXXXXXXXXXXXXXXXXXX
                       XXXXXXXX XXXXXXXXXXXXXXXXXXX
                       XXXXXXXXXXXXXXXXXXXXXXXXX
                       BB BBBBBBBBBBBBBBBXXXXXXXBBBBBX
              BBBBB
      XXXXXX XXXXXXXXXXXXXXXX
      XXXXXXXX
      
      XXXXXX
    XXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBB
        XX XXXXXXXXX XXXXXXXXXXXXX
      BBBBB
      XX XXXXXXXXX XXXXXXXXXXXXXXX
    XXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
      
      XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXX XXXXXXXXXXX
      XXXX
    BBBBB
  XXXXXX
XXXXXX
BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBB BBBBBBBBBBBBBBBBBB

