BBBB BBBB BBBBBBBBBBBBBBBB
XXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX BB BBBBBBBBBBXXBBBBBX XXXXXXXXXXXX BBBBBBBBBBB BBBB BX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBB
      XXX
         gettext(u'Description') X
      XXXX
      XXX
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      XXXX
    BBBBB
    BBB BBBB BB BBBBBBBBBBBBBBBBBBBBB
        BB BBBBBBBBBBBBB
        XXX gettext(u'Responsible contact person(s)') X XXXX
        BBBBB
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBB
    BBBBBB
    BB BBB BBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXX gettext(u'Please give additional information if needed') X XXXXXXXX
        XXXXXXXXX XXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX BB BBBBBBBBB BB BBBBBBBBXXXXXXXXXXXXXXXXXBBBBB XXXXXXXXXXXXX
                  XXXXXXXXXBB BBBBBBBBBBBBBBBXXXXXXXXXXX
      XXXXXX
    BBBBB
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX
XXXXXX