BBBB BBBB

XXX
   XXXX
  BB BBB BBBBBBBBBBBBBBBBBBBBBB
    BB BBBBBBB
      XXX gettext(u'Email') XXXXX XXXX
    BBBBB
    BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      BB BBBBBBBBBBBBBB
        XXX gettext(u'Phone') XXXXX XXXX
      BBBBB
      BB BBBBBBBBB
        XXX gettext(u'Address') XXXXX XXXXFFFFFFFFFFFF
      BBBBB
    BBBBB
  BBBBB
XXXX