BBBB BBBB
BB BBBBBBBBBBB

BBBBB
BB B 
XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
XXXXXXX gettext(u'Contact details') X

 
BB BBBBBBBBBBBBBBBBB gettext(u'Email') X 
BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB gettext(u'Phone') X 
BBBBBBB BBBBBBBBBBBBBBBBBBB
 gettext(u'Address') X
BBBBB
XXXXXX
BBBBB