# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='publish_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
