# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-02-26 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_contest_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='login_required',
            field=models.BooleanField(default=False),
        ),
    ]
