
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "42fc77c30b970ad0c0ded5f5b0ab8d26690467a2",
 "version": "7.0.0.beta1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
