
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-05-31T11:40:13+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "55a05fb17b20d60003529f461118766b74116e2e",
 "version": "v0.1.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
