
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-05-19T22:26:41+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "da08b46bbe75c5af4db9561ab37b67dc296dabaf",
 "version": "1.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
