# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-12 09:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slothTw', '0011_auto_20170606_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='likesfromuser',
            name='course',
            field=models.ManyToManyField(to='slothTw.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='dept',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pagelog',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='slothTw.Course'),
        ),
        migrations.AddField(
            model_name='pagelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slothTw.LikesFromUser'),
        ),
    ]
