
# This file was generated by PyScaffold from the git
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.4.1'
version_full = '57f77de0a4e9f73ea85c4729d3985ebae01af0d8'
def get_versions(default=dict(), verbose=False):
    return dict(version=version_version, full=version_full)
