#encoding: utf-8
'''
Created on Mar 2": u" 2017

@author:  Tim
'''

timitToIPA = {u"ng": u"ŋ",
              u"sh": u"ʃ",
              u"ch": u"tʃ",
              u"y": u"j",
              u"zj": u"ʒ",
              u"jh": u"dʒ",
              u"dh": u"ð",
              u"th": u"θ",
              u"p": u"p",
              u"b": u"b",
              u"m": u"m",
              u"t": u"t",
              u"d": u"d",
              u"n": u"n",
              u"k": u"k",
              u"g": u"g",
              u"s": u"s",
              u"z": u"z",
              u"f": u"f",
              u"v": u"v",
              u"w": u"w",
              u"l": u"l",
              u"r": u"r",
              u"aa": u"ɑ",
              u"h": u"h",
              u"ae": u"æ",
              u"ah0": u"ə",
              u"ah1": u"ʌ",
              u"ao": u"ɔ",
              u"eh": u"ɛ",
              u"ih": u"ɪ",
              u"iy": u"i",
              u"uh": u"ʊ",
              u"uw": u"u",
              u"ay": u"aɪ",
              u"aw": u"aʊ",
              u"ey": u"eɪ",
              u"ow": u"oʊ",
              u"oy": u"ɔɪ",
              u"er0": u"ɚ",
              u"er1": u"ɝ",
              }
