BBBB BBBB BBBBBBBBBBBBBBBB
XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXX XXX XXXXXX XXX XXXXXXX XXX XXXXXX XXXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXX gettext(u'Toggle navigation') XXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXX
      BBBBB BBBBBBBBBBBB
        XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      BBBBBBBB
    XXXXXX

    XXXX XXXXXXX XXX XXX XXXXXX XXXXXX XXX XXXXX XXXXXXX XXX XXXXXXXX XXX
    BBBBBBBBBB BBBBBBBBBBB BB BBBBBBB
    BBBBB BBBBBBBBBBB
      XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXX XXXXXXXXXXXX
        BBB BBBB BB BBBBBBBBBBBB
          BB BBBBBBBBBBBBBB
            XXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXX
                    XXXXXXXXXXXXXXXXX gettext(u'current') XXXXXXXXXXXXXXXXX
          BBBB
            XXXXXX XXXXXXXXXXXXXXXXX
          BBBBB
        BBBBBB
      XXXXX
    BBBBBBBB

    BBBBB BBBBBBBBBBBB
      XXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
        BBB BBBB BB BBBBBBBBBBBBB
          BB BBBBBBBBBBBBBB
            XXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXX
                    XXXXXXXXXXXXXXXXX gettext(u'current') XXXXXXXXXXXXXXXXX
          BBBB
            XXXXXX XXXXXXXXXXXXXXXXX
          BBBBB
        BBBBBB
      XXXXX
    BBBBBBBB
    XXXXXXXXXX XXXXXXXXXXXXXXXXX XXX
  XXXXXXXXXX XXXXXXXXXXXXXXXXX XXX
XXXXXX