BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBB

XXXX XXXXXXXXXXXXXXXXX gettext(u'Are you sure you want to delete your participation permanently from the system?') XXXXXX
BBBBBB BBBB
BBBBBBBB