BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBBBBBBBBBBBBB
BBBBB BBBBBB
BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBB
BBBBBBBB
BBBBB BBBBBBB
  XXXX
  BB BBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBB BBBBBBBBBBBBB
    BBBBBBBB
  BBBB
    XXXX gettext(u'Form is not public at the moment.') XXXXX
  BBBBB
BBBBBBBB