BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBB BBBBBB BBBB BBBBBBBBBBBBBBBB
BBBBB BBB
  BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBBB BBB
      XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    BBBBBBBBBBB
  BBBBB
  
BBBBBBBB
BBBBB BBBBBB
  BB BBB BBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
      BBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBB
      BBB B BB BBBBBBB
        XXX XXXXXXXXXXXXXXXXXXX XXXXXXX
        BB BBBBBBBBBBBBBBXXXXXXXXBBBBB
        BB BBBBBBBBBBBBBBBBBBBBB
        BB BBBBBBBBBBBBBBBXXXXXXBBBBB
        XX
        BB BBBBBBBBBBBBBBBB
        XX XXXXXXXXXXXXX
        BBBB
        XX XXXXXXXXXXXX
        BBBBB
        XXXXX
      BBBBBB
    XXXXX
    XXXXXX
  BBBBB
BBBBBBBB
