BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBBBBBBBBBBBBB
BBBBB BBBBBBB
  
  
    XXXX XXXXXXXXXXXXXXXXX gettext(u'Please check that the given data is correct ') XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX gettext(u'Contact details') SSSSSSS SSSSSSSXXXXXX

    BBB BBBBBBB BBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          FFFFFFFFFF
        XXXXXX
      XXXXXX
    BBBBBB

      XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXXX
             XXXXXXBBB BBBBBBBBBBBBBBBBBXX gettext(u'Change contact details') XXXX
        XXXXXX
      XXXXXX
  XXXXXX
  
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX gettext(u'I am wishing to participate in the following activities') S SS SSSSSSS SS SSSSSSSSSSS SS SSS SSSSSSSSS SSSSSSSSSSXXXXXX
    XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXX
         gettext(u'Activity') 
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXX
         gettext(u'Additional info') 
      XXXXXX
    XXXXXX

    BBB B BB BBBBBBBBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          FFFFFFFFFF
        XXXXXX
      XXXXXX
      BBB B BB BBBBBBBBB
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            FFFFFFFFFF
          XXXXXX
        XXXXXX
      BBBBBB
    BBBBBB
      XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXXX
             XXXXXXBBB BBBBBBBBBBBBBBBXX gettext(u'Adjust participation information') XXXX
        XXXXXX
      XXXXXX
  XXXXXX
  
  BB BBBBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX gettext(u'Answers to questions') SSSSSSS SS SSSSSSSSSXXXXXX
      XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
           gettext(u'Question') 
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
           gettext(u'Answer') 
        XXXXXX
      XXXXXX
      BBB B BB BBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBB
              BB BBBBBBBB
                 gettext(u'Yes') 
              BBBB
                 gettext(u'No') 
              BBBBB
            BBBB
              FFFFFFFFFF
            BBBBB
          XXXXXX
        XXXXXX
      BBBBBB
        XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXX
               XXXXXXBBB BBBBBBBBBBBXX gettext(u'Modify question answers') XXXX
          XXXXXX
        XXXXXX
    XXXXXX
  BBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX gettext(u'Are you ready to send data?') XXXXX
      XXXXX XXXXXXXXX XXXXXXXXXXXXXX
        BBBBBBBBBB
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'Send data!') XXX
          XXXXXX
        XXXXXX
      XXXXXXX
    XXXXXX
BBBBBBBB