
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "c55c82683bd3f58574a5a9141b7730a8a6008ce2",
 "version": "0.0.0a44"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
