
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "18f5dc9b37db4388202e482ee0142e742e76a3b8",
 "version": "0.24"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
