# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-23 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slothTw', '0004_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='benchmark',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='course',
            name='syllabus',
            field=models.CharField(default='', max_length=50),
        ),
    ]
