# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addFilter.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FiltersDialog(object):
    def setupUi(self, FiltersDialog):
        FiltersDialog.setObjectName("FiltersDialog")
        FiltersDialog.resize(640, 480)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(FiltersDialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_filters = QtWidgets.QWidget(FiltersDialog)
        self.widget_filters.setObjectName("widget_filters")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_filters)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.table_filters = QtWidgets.QTableWidget(self.widget_filters)
        self.table_filters.setShowGrid(False)
        self.table_filters.setColumnCount(1)
        self.table_filters.setObjectName("table_filters")
        self.table_filters.setRowCount(0)
        self.table_filters.horizontalHeader().setVisible(False)
        self.table_filters.horizontalHeader().setStretchLastSection(True)
        self.table_filters.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.table_filters)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.widget_filters)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.list_columns = QtWidgets.QListWidget(self.widget_filters)
        self.list_columns.setObjectName("list_columns")
        self.verticalLayout_5.addWidget(self.list_columns)
        self.check_before_transformation = QtWidgets.QCheckBox(self.widget_filters)
        self.check_before_transformation.setObjectName("check_before_transformation")
        self.verticalLayout_5.addWidget(self.check_before_transformation)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.line = QtWidgets.QFrame(self.widget_filters)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.widget_filters)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.radio_OP_EQ = QtWidgets.QRadioButton(self.widget_filters)
        self.radio_OP_EQ.setChecked(True)
        self.radio_OP_EQ.setObjectName("radio_OP_EQ")
        self.verticalLayout.addWidget(self.radio_OP_EQ)
        self.radio_OP_NE = QtWidgets.QRadioButton(self.widget_filters)
        self.radio_OP_NE.setObjectName("radio_OP_NE")
        self.verticalLayout.addWidget(self.radio_OP_NE)
        self.radio_OP_LT = QtWidgets.QRadioButton(self.widget_filters)
        self.radio_OP_LT.setObjectName("radio_OP_LT")
        self.verticalLayout.addWidget(self.radio_OP_LT)
        self.radio_OP_LE = QtWidgets.QRadioButton(self.widget_filters)
        self.radio_OP_LE.setObjectName("radio_OP_LE")
        self.verticalLayout.addWidget(self.radio_OP_LE)
        self.radio_OP_GT = QtWidgets.QRadioButton(self.widget_filters)
        self.radio_OP_GT.setObjectName("radio_OP_GT")
        self.verticalLayout.addWidget(self.radio_OP_GT)
        self.radio_OP_GE = QtWidgets.QRadioButton(self.widget_filters)
        self.radio_OP_GE.setObjectName("radio_OP_GE")
        self.verticalLayout.addWidget(self.radio_OP_GE)
        self.radio_OP_MATCH = QtWidgets.QRadioButton(self.widget_filters)
        self.radio_OP_MATCH.setObjectName("radio_OP_MATCH")
        self.verticalLayout.addWidget(self.radio_OP_MATCH)
        self.radio_OP_NMATCH = QtWidgets.QRadioButton(self.widget_filters)
        self.radio_OP_NMATCH.setObjectName("radio_OP_NMATCH")
        self.verticalLayout.addWidget(self.radio_OP_NMATCH)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.line_2 = QtWidgets.QFrame(self.widget_filters)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget_filters)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.edit_value = QtWidgets.QLineEdit(self.widget_filters)
        self.edit_value.setObjectName("edit_value")
        self.verticalLayout_2.addWidget(self.edit_value)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.button_add = QtWidgets.QPushButton(self.widget_filters)
        self.button_add.setObjectName("button_add")
        self.verticalLayout_2.addWidget(self.button_add)
        self.button_remove = QtWidgets.QPushButton(self.widget_filters)
        self.button_remove.setObjectName("button_remove")
        self.verticalLayout_2.addWidget(self.button_remove)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addWidget(self.widget_filters)
        self.buttonBox = QtWidgets.QDialogButtonBox(FiltersDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_4.addWidget(self.buttonBox)
        self.label_2.setBuddy(self.list_columns)
        self.label_3.setBuddy(self.radio_OP_EQ)
        self.label.setBuddy(self.edit_value)

        self.retranslateUi(FiltersDialog)
        self.buttonBox.accepted.connect(FiltersDialog.accept)
        self.buttonBox.rejected.connect(FiltersDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(FiltersDialog)

    def retranslateUi(self, FiltersDialog):
        _translate = QtCore.QCoreApplication.translate
        FiltersDialog.setWindowTitle(_translate("FiltersDialog", "Summary filters – Coquery"))
        self.label_2.setText(_translate("FiltersDialog", "&Column:"))
        self.check_before_transformation.setText(_translate("FiltersDialog", "&Apply before transformation"))
        self.label_3.setText(_translate("FiltersDialog", "&Relation:"))
        self.radio_OP_EQ.setText(_translate("FiltersDialog", "equals"))
        self.radio_OP_NE.setText(_translate("FiltersDialog", "does not equal"))
        self.radio_OP_LT.setText(_translate("FiltersDialog", "is less than"))
        self.radio_OP_LE.setText(_translate("FiltersDialog", "is less or equal than"))
        self.radio_OP_GT.setText(_translate("FiltersDialog", "is greater than"))
        self.radio_OP_GE.setText(_translate("FiltersDialog", "is greater or equal than"))
        self.radio_OP_MATCH.setText(_translate("FiltersDialog", "matches"))
        self.radio_OP_NMATCH.setText(_translate("FiltersDialog", "does not match"))
        self.label.setText(_translate("FiltersDialog", "&Value:"))
        self.button_add.setText(_translate("FiltersDialog", "&Add"))
        self.button_remove.setText(_translate("FiltersDialog", "&Remove"))


