# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'csvOptions.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FileOptions(object):
    def setupUi(self, FileOptions):
        FileOptions.setObjectName("FileOptions")
        FileOptions.resize(640, 480)
        FileOptions.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(FileOptions)
        self.verticalLayout_2.setContentsMargins(4, -1, 4, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.OptionsBox = QtWidgets.QGroupBox(FileOptions)
        self.OptionsBox.setObjectName("OptionsBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.OptionsBox)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.OptionsBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.edit_file_name = QtWidgets.QLineEdit(self.OptionsBox)
        self.edit_file_name.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_file_name.sizePolicy().hasHeightForWidth())
        self.edit_file_name.setSizePolicy(sizePolicy)
        self.edit_file_name.setAccessibleDescription("")
        self.edit_file_name.setObjectName("edit_file_name")
        self.horizontalLayout.addWidget(self.edit_file_name)
        self.button_browse_file = QtWidgets.QPushButton(self.OptionsBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_browse_file.sizePolicy().hasHeightForWidth())
        self.button_browse_file.setSizePolicy(sizePolicy)
        self.button_browse_file.setObjectName("button_browse_file")
        self.horizontalLayout.addWidget(self.button_browse_file)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.separate_char = QtWidgets.QComboBox(self.OptionsBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.separate_char.sizePolicy().hasHeightForWidth())
        self.separate_char.setSizePolicy(sizePolicy)
        self.separate_char.setEditable(True)
        self.separate_char.setObjectName("separate_char")
        self.separate_char.addItem("")
        self.separate_char.addItem("")
        self.separate_char.addItem("")
        self.separate_char.addItem("")
        self.separate_char.addItem("")
        self.separate_char.addItem("")
        self.gridLayout.addWidget(self.separate_char, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.OptionsBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.file_has_headers = QtWidgets.QCheckBox(self.OptionsBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_has_headers.sizePolicy().hasHeightForWidth())
        self.file_has_headers.setSizePolicy(sizePolicy)
        self.file_has_headers.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.file_has_headers.setText("")
        self.file_has_headers.setObjectName("file_has_headers")
        self.gridLayout.addWidget(self.file_has_headers, 3, 1, 1, 1)
        self.query_column = QtWidgets.QSpinBox(self.OptionsBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.query_column.sizePolicy().hasHeightForWidth())
        self.query_column.setSizePolicy(sizePolicy)
        self.query_column.setMinimum(1)
        self.query_column.setMaximum(999)
        self.query_column.setObjectName("query_column")
        self.gridLayout.addWidget(self.query_column, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.OptionsBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 6, 0, 1, 1)
        self.combo_encoding = QtWidgets.QComboBox(self.OptionsBox)
        self.combo_encoding.setObjectName("combo_encoding")
        self.gridLayout.addWidget(self.combo_encoding, 6, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.OptionsBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.ignore_lines = QtWidgets.QSpinBox(self.OptionsBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ignore_lines.sizePolicy().hasHeightForWidth())
        self.ignore_lines.setSizePolicy(sizePolicy)
        self.ignore_lines.setObjectName("ignore_lines")
        self.gridLayout.addWidget(self.ignore_lines, 4, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.OptionsBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)
        self.label_query_column = QtWidgets.QLabel(self.OptionsBox)
        self.label_query_column.setObjectName("label_query_column")
        self.gridLayout.addWidget(self.label_query_column, 1, 0, 1, 1)
        self.quote_char = QtWidgets.QComboBox(self.OptionsBox)
        self.quote_char.setObjectName("quote_char")
        self.gridLayout.addWidget(self.quote_char, 5, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.OptionsBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addWidget(self.OptionsBox)
        self.FilePreviewArea = QtWidgets.QTableView(FileOptions)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FilePreviewArea.sizePolicy().hasHeightForWidth())
        self.FilePreviewArea.setSizePolicy(sizePolicy)
        self.FilePreviewArea.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.FilePreviewArea.setEditTriggers(QtWidgets.QAbstractItemView.SelectedClicked)
        self.FilePreviewArea.setAlternatingRowColors(True)
        self.FilePreviewArea.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectColumns)
        self.FilePreviewArea.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.FilePreviewArea.setObjectName("FilePreviewArea")
        self.verticalLayout_2.addWidget(self.FilePreviewArea)
        self.buttonBox = QtWidgets.QDialogButtonBox(FileOptions)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout_2.setStretch(1, 1)
        self.label_4.setBuddy(self.edit_file_name)
        self.label.setBuddy(self.file_has_headers)
        self.label_3.setBuddy(self.combo_encoding)
        self.label_6.setBuddy(self.ignore_lines)
        self.label_2.setBuddy(self.quote_char)
        self.label_query_column.setBuddy(self.query_column)
        self.label_10.setBuddy(self.separate_char)

        self.retranslateUi(FileOptions)
        self.buttonBox.accepted.connect(FileOptions.accept)
        self.buttonBox.rejected.connect(FileOptions.reject)
        QtCore.QMetaObject.connectSlotsByName(FileOptions)

    def retranslateUi(self, FileOptions):
        _translate = QtCore.QCoreApplication.translate
        FileOptions.setWindowTitle(_translate("FileOptions", "Input file options"))
        self.label_4.setText(_translate("FileOptions", "File na&me:"))
        self.edit_file_name.setPlaceholderText(_translate("FileOptions", "Input file name"))
        self.button_browse_file.setText(_translate("FileOptions", "&Browse"))
        self.button_browse_file.setShortcut(_translate("FileOptions", "Alt+B"))
        self.separate_char.setItemText(0, _translate("FileOptions", ","))
        self.separate_char.setItemText(1, _translate("FileOptions", ";"))
        self.separate_char.setItemText(2, _translate("FileOptions", ":"))
        self.separate_char.setItemText(3, _translate("FileOptions", "#"))
        self.separate_char.setItemText(4, _translate("FileOptions", "{tab}"))
        self.separate_char.setItemText(5, _translate("FileOptions", "{space}"))
        self.label.setText(_translate("FileOptions", "Fi&le contains header:"))
        self.label_3.setText(_translate("FileOptions", "&Character encoding:"))
        self.label_6.setText(_translate("FileOptions", "&Text lines to ignore after header:"))
        self.label_2.setText(_translate("FileOptions", "&Quote character:"))
        self.label_query_column.setText(_translate("FileOptions", "&Read queries from column number:"))
        self.label_10.setText(_translate("FileOptions", "Character that &separates columns:"))


