# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-25 03:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw', models.CharField(max_length=500)),
                ('html', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('avatar', models.ImageField(default='', upload_to='')),
                ('teacher', models.CharField(max_length=10)),
                ('school', models.CharField(max_length=10)),
                ('book', models.CharField(max_length=50)),
                ('syllabus', models.CharField(max_length=50)),
                ('feedback_amount', models.PositiveIntegerField(default=0)),
                ('feedback_freedom', models.FloatField(default=0)),
                ('feedback_FU', models.FloatField(default=0)),
                ('feedback_easy', models.FloatField(default=0)),
                ('feedback_GPA', models.FloatField(default=0)),
                ('feedback_knowledgeable', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slothTw.Course'),
        ),
    ]
