# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-24 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpmenu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractbasemenu',
            name='displayType',
            field=models.CharField(blank=True, choices=[('Title', 'Title'), ('Icon', 'Icon'), ('IconTitle', 'IconTitle'), ('Button', 'Button'), ('IconBadge', 'IconBadge'), ('IconTitleBadge', 'IconTitleBadge')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='abstractbasemenu',
            name='icon',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='abstractbasemenu',
            name='section',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
